/* ============================================================
   VR LAYER (Quest 3 and any WebXR headset) · v1
   - Left stick: walk where you LOOK (head-relative), through the same ground + collision as desktop (no sinking, no
     walking through stairs). Right stick: snap turn 30°. Left stick click / right stick click: run.
   - Hands: metallic robot hands on both controllers. Right hand: laser pointer; trigger = tap what it points at
     (hotspots, products, signs). A = do the nearest thing (same as the green button on screen). B = bug report.
   - Wrist menu (left controller, press X or Y to toggle): 🎢 Coaster · 🏖️ Beach · 🕷️ Spiders · 🌍 Globe · 📍 Directory
     places · 🐞 Bug report · 🚪 Exit VR. Point with the laser, pull the trigger.
   - Bug report: press B (or the menu) → captures where you are, what is near, time, headset; a marker drops in the
     world and the report queues; the form opens when you leave VR. Shake-free, no screenshots needed.
   - Sharper: XR framebuffer scale 1.2 and foveation on, so text and metal look crisp.
   ============================================================ */
import { THREE, makeTextTexture } from './wvm-engine.js';
const T = THREE;
const M = (c, o = {}) => new T.MeshStandardMaterial(Object.assign({ color: c, roughness: 0.3, metalness: 0.9 }, o));
export function makeRobotHand(side, col = 0xcfd8e3) { const g = new T.Group(); const metal = M(col); const dark = M(0x2a3140, { roughness: 0.5, metalness: 0.7 }); const palm = new T.Mesh(new T.BoxGeometry(0.075, 0.03, 0.09), metal); palm.position.set(0, 0, -0.02); g.add(palm); const wrist = new T.Mesh(new T.CylinderGeometry(0.03, 0.035, 0.05, 12), dark); wrist.rotation.x = Math.PI / 2; wrist.position.set(0, 0, 0.045); g.add(wrist); const fingers = []; for (let i = 0; i < 4; i++) { const f = new T.Group(); f.position.set(-0.03 + i * 0.02, 0, -0.065); g.add(f); const s1 = new T.Mesh(new T.BoxGeometry(0.014, 0.014, 0.035), metal); s1.position.z = -0.017; f.add(s1); const k = new T.Group(); k.position.z = -0.035; f.add(k); const s2 = new T.Mesh(new T.BoxGeometry(0.012, 0.012, 0.03), metal); s2.position.z = -0.015; k.add(s2); const tip = new T.Mesh(new T.SphereGeometry(0.007, 8, 6), dark); tip.position.z = -0.03; k.add(tip); fingers.push({ f, k }); } const th = new T.Group(); th.position.set(side === 'left' ? 0.04 : -0.04, 0, -0.02); th.rotation.y = side === 'left' ? -0.9 : 0.9; g.add(th); const t1 = new T.Mesh(new T.BoxGeometry(0.014, 0.014, 0.03), metal); t1.position.z = -0.015; th.add(t1); const t2 = new T.Mesh(new T.BoxGeometry(0.012, 0.012, 0.025), metal); t2.position.z = -0.042; th.add(t2); const led = new T.Mesh(new T.SphereGeometry(0.006, 8, 6), new T.MeshStandardMaterial({ color: 0x38f0ff, emissive: 0x38f0ff, emissiveIntensity: 2 })); led.position.set(0, 0.018, -0.01); g.add(led); g.userData.fingers = fingers; g.userData.thumb = th; g.userData.led = led; g.userData.grip = (k) => { fingers.forEach(({ f, k: kn }) => { f.rotation.x = k * 1.2; kn.rotation.x = k * 1.4; }); th.rotation.z = (side === 'left' ? -1 : 1) * k * 0.8; }; return g; }
export function initXR(app, opts = {}) {
  const R = app.renderer; const toast = (m, ms) => app.toast(m, ms); if (!R || !R.xr) return; try { R.xr.setFramebufferScaleFactor(1.2); } catch (e) { } try { R.xr.setFoveation(1); } catch (e) { }
  const rig = app.rig; const ctl = [0, 1].map(i => R.xr.getController(i)); const grips = [0, 1].map(i => R.xr.getControllerGrip(i)); ctl.forEach(c => rig.add(c)); grips.forEach(g => rig.add(g)); const hands = {}; const hand = (src) => { if (!src || hands[src.handedness]) return; const h = makeRobotHand(src.handedness); h.rotation.x = -0.4; hands[src.handedness] = h; const gi = ctl.findIndex(c => c.userData.src === src); (gi >= 0 ? grips[gi] : grips[src.handedness === 'left' ? 0 : 1]).add(h); };
  // laser on the right hand
  const laser = new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(0, 0, 0), new T.Vector3(0, 0, -8)]), new T.LineBasicMaterial({ color: 0x38f0ff, transparent: true, opacity: 0.85 })); laser.visible = false; const dot = new T.Mesh(new T.SphereGeometry(0.025, 10, 8), new T.MeshStandardMaterial({ color: 0xffffff, emissive: 0x38f0ff, emissiveIntensity: 2 })); dot.visible = false; app.scene.add(dot); let rightCtl = null, leftCtl = null;
  ctl.forEach((c, i) => { c.addEventListener('connected', (e) => { c.userData.src = e.data; if (e.data.handedness === 'right') { rightCtl = c; c.add(laser); laser.visible = true; } else leftCtl = c; hand(e.data); if (hands[e.data.handedness]) { c.userData.hand = hands[e.data.handedness]; } }); c.addEventListener('disconnected', () => { c.userData.src = null; }); c.addEventListener('selectstart', () => { if (c === rightCtl) select(); else actNearest(); }); c.addEventListener('squeezestart', () => { const h = c.userData.hand; h && h.userData.grip(1); }); c.addEventListener('squeezeend', () => { const h = c.userData.hand; h && h.userData.grip(0); }); });
  /* ---- the wrist menu ---- */
  const menu = new T.Group(); menu.visible = false; rig.add(menu); const items = []; const mkBtn = (label, fn, i, n, w = 0.26) => { const tex = makeTextTexture([label], { w: 1024, h: 220, bg: 'rgba(8,20,50,0.92)', fg: '#fff', accent: '#38f0ff', font: 'bold 76px Poppins, Arial', radius: 60, border: '#38f0ff', glow: false }); const m = new T.Mesh(new T.PlaneGeometry(w, w * 0.22), new T.MeshBasicMaterial({ map: tex, transparent: true })); m.position.set(0, (n / 2 - i - 0.5) * 0.065, 0); m.userData.vrfn = fn; m.userData.label = label; menu.add(m); items.push(m); return m; };
  const places = () => (app.places || []).filter(p => p.top || /coaster|beach|spider|globe|lake|zoo|wilds|showroom|gallery|arcade|observatory|unity|pool|jamoke|mount|snowboard|hub|plaza/i.test(p.id + ' ' + p.name)).slice(0, 10);
  const buildMenu = () => { items.splice(0).forEach(m => menu.remove(m)); const rows = [['🎢 Ride the coaster', rideCoaster], ...(opts.extra || []), ...places().map(p => [p.icon + ' ' + p.name.replace(/·.*$/, '').slice(0, 26), () => goPlace(p)]), ['🐞 Report a bug (B)', bug], ['🚪 Exit VR', () => { const s = R.xr.getSession(); s && s.end(); }]]; const n = rows.length; rows.forEach(([l, f], i) => mkBtn(l, f, i, n)); const back = new T.Mesh(new T.PlaneGeometry(0.3, n * 0.065 + 0.04), new T.MeshBasicMaterial({ color: 0x050b1e, transparent: true, opacity: 0.6 })); back.position.z = -0.005; menu.add(back); items.push(back); };
  const goPlace = (p) => { app.player.position.set(p.x, app.opts && app.opts.groundY ? app.opts.groundY(p.x, p.z) : 0, p.z); if (p.yaw !== undefined) app.yaw = p.yaw; app.walkTarget = null; toast('✨ ' + p.name, 2000); menu.visible = false; };
  const rideCoaster = () => { const it = (app.interactables || []).filter(i => /coaster|chiller|aurora|blaster|ride|peace coaster/i.test(i.label || '') && !/jet ski|snowboard|elevator|lift|cart|boat|gondola/i.test(i.label || '')); const pick = it[0]; const pl = (app.places || []).find(p => /coaster/i.test(p.id + ' ' + p.name)); if (pl) goPlace(pl); if (pick) { app.player.position.set(pick.x, app.opts && app.opts.groundY ? app.opts.groundY(pick.x, pick.z) : app.player.position.y, pick.z + 1); setTimeout(() => { try { pick.fn(app); toast('🎢 Hold on.', 2000); } catch (e) { } }, 600); } else toast('🎢 Walk to the coaster station and press A.', 3000); menu.visible = false; };
  const bugs = JSON.parse(localStorage.getItem('vr_bugs') || '[]'); const bug = () => { const P = app.player.position; const near = (app.places || []).map(p => [Math.hypot(p.x - P.x, p.z - P.z), p]).sort((a, b) => a[0] - b[0])[0]; const rep = { t: new Date().toISOString(), x: Math.round(P.x), y: Math.round(P.y * 10) / 10, z: Math.round(P.z), yaw: Math.round(app.yaw * 100) / 100, near: near ? near[1].name : '', act: app._act ? app._act.label : '', ride: !!app.ride, ua: navigator.userAgent.slice(0, 80), page: location.pathname }; bugs.push(rep); localStorage.setItem('vr_bugs', JSON.stringify(bugs.slice(-40))); const mk = new T.Mesh(new T.ConeGeometry(0.25, 0.8, 8), new T.MeshStandardMaterial({ color: 0xff4f79, emissive: 0xff4f79, emissiveIntensity: 1 })); mk.position.set(P.x, P.y + 1.2, P.z); app.scene.add(mk); const lbl = new T.Mesh(new T.PlaneGeometry(1.2, 0.3), new T.MeshBasicMaterial({ map: makeTextTexture(['🐞 bug #' + bugs.length + ' logged'], { w: 1024, h: 256, bg: 'rgba(255,79,121,0.9)', fg: '#fff', accent: '#fff', font: 'bold 90px Poppins, Arial' }), transparent: true })); lbl.position.set(P.x, P.y + 1.9, P.z); app.scene.add(lbl); app.onUpdate(() => { const cam = R.xr.getCamera(); lbl.lookAt(cam.position); }); toast('🐞 Bug #' + bugs.length + ' logged with your position. The form opens when you leave VR.', 3500); if (navigator.vibrate) navigator.vibrate(60); try { const src = (R.xr.getSession() || {}).inputSources || []; for (const s of src) s.gamepad && s.gamepad.hapticActuators && s.gamepad.hapticActuators[0] && s.gamepad.hapticActuators[0].pulse(0.7, 120); } catch (e) { } };
  const actNearest = () => { if (app._act && app._act.fn) { try { app._act.fn(app); if (navigator.vibrate) navigator.vibrate(20); } catch (e) { } } else toast('Nothing to do right here. Walk closer to something.', 1500); };
  const ray = new T.Raycaster(); const tmpM = new T.Matrix4(); const select = () => { if (!rightCtl) return; tmpM.identity().extractRotation(rightCtl.matrixWorld); ray.ray.origin.setFromMatrixPosition(rightCtl.matrixWorld); ray.ray.direction.set(0, 0, -1).applyMatrix4(tmpM); if (menu.visible) { const mh = ray.intersectObjects(items, false); if (mh.length && mh[0].object.userData.vrfn) { mh[0].object.userData.vrfn(); return; } } const hits = ray.intersectObjects(app.hotspots || [], true); if (hits.length) { let o = hits[0].object; while (o && !o.userData.hotspot) o = o.parent; if (o && o.userData.hotspot) { try { app._activate(o.userData.hotspot, hits[0]); } catch (e) { const h = o.userData.hotspot; h.fn && h.fn(app); } return; } } actNearest(); };
  /* ---- per frame: sticks, buttons, laser dot, menu follow ---- */
  let snapT = 0, menuT = 0, bT = 0; const headDir = new T.Vector3(); const poll = (dt) => { if (!R.xr.isPresenting) return; const s = R.xr.getSession(); if (!s) return; app.xrMove && app.xrMove.set(0, 0); const cam = R.xr.getCamera(); cam.getWorldDirection(headDir); const headYaw = Math.atan2(-headDir.x, -headDir.z); const rel = headYaw - app.yaw; let run = false;
    for (const src of s.inputSources) { const gp = src.gamepad; if (!gp) continue; const ax = gp.axes; const x = ax[2] ?? ax[0] ?? 0, y = ax[3] ?? ax[1] ?? 0; const b = gp.buttons; if (src.handedness === 'left') { if (Math.hypot(x, y) > 0.15 && app.xrMove) { const mx = x, my = -y; app.xrMove.x += mx * Math.cos(rel) - my * Math.sin(rel); app.xrMove.y += mx * Math.sin(rel) + my * Math.cos(rel); } if (b[3]?.pressed) run = true; if ((b[4]?.pressed || b[5]?.pressed) && app.t - menuT > 0.5) { menuT = app.t; menu.visible = !menu.visible; if (menu.visible) buildMenu(); } } else { snapT -= dt; if (Math.abs(x) > 0.6 && snapT <= 0) { app.yaw -= Math.sign(x) * Math.PI / 6; snapT = 0.3; } if (Math.abs(x) < 0.3) snapT = 0; if (b[3]?.pressed) run = true; if (b[4]?.pressed && app.t - bT > 1) { bT = app.t; actNearest(); } if (b[5]?.pressed && app.t - bT > 1) { bT = app.t; bug(); } } const h = hands[src.handedness]; if (h && h.userData.led) h.userData.led.material.emissiveIntensity = 1 + (b[0]?.value || 0) * 3; if (h && b[0]) h.userData.grip(Math.max(b[0].value || 0, b[1]?.value || 0)); }
    app.running = run; if (app.xrMove && app.xrMove.lengthSq() > 0.02) app.moving = true;
    if (rightCtl && laser.visible) { tmpM.identity().extractRotation(rightCtl.matrixWorld); ray.ray.origin.setFromMatrixPosition(rightCtl.matrixWorld); ray.ray.direction.set(0, 0, -1).applyMatrix4(tmpM); const hits = ray.intersectObjects((menu.visible ? items : []).concat(app.hotspots || []), true); if (hits.length) { dot.visible = true; dot.position.copy(hits[0].point); laser.scale.z = hits[0].distance / 8; laser.material.color.setHex(0xffd23f); } else { dot.visible = false; laser.scale.z = 1; laser.material.color.setHex(0x38f0ff); } }
    if (menu.visible && leftCtl) { menu.position.copy(leftCtl.position).add(new T.Vector3(0, 0.12, -0.05)); menu.quaternion.copy(cam.quaternion); } };
  app.onUpdate(poll);
  R.xr.addEventListener('sessionstart', () => { setTimeout(() => toast('🕶️ VR: left stick walks where you look · right stick turns · trigger taps · A does the nearest thing · X/Y opens the wrist menu · B logs a bug.', 7000), 800); try { if (app.avatar) app.avatar.visible = false; } catch (e) { } });
  R.xr.addEventListener('sessionend', () => { menu.visible = false; if (bugs.length && opts.onBugs) opts.onBugs(bugs.slice()); });
  return { menu, bug, rideCoaster };
}
