/* ============================================================
   WORLD VR MALL · fun2 (v5.6)
   - 🕷️ Spider World: Stephany's pavilion. Real-looking spiders of every size, all unique, walking a web-covered dome;
     tap any spider for its species card (what it is, what it eats, why it helps). The orb-weaver photo on the wall.
   - 🌍 The globe hologram is a portal: spin it, pick a pin, go (allofus.one, the mall, gallery, beach, lake, showroom, spiders, games)
   - Quick ports in the dock: 🏠 allofus.one · 🏖️ Beach · 🕷️ Spiders
   - 🛒 Shopping-cart character modes: neon, giant tires, color
   - 🎢 Coaster FOV punch on the fast parts
   ============================================================ */
import { THREE, makeSprite, makeTextTexture, isMobile, pick } from './wvm-engine.js';
const T = THREE; const MOB = isMobile();
const M = (c, o = {}) => new T.MeshStandardMaterial(Object.assign({ color: c, roughness: 0.75 }, o)); const glow = (c, k = 1.2) => new T.MeshStandardMaterial({ color: c, emissive: c, emissiveIntensity: k, roughness: 0.4 });
const box = (w, h, d, m, x, y, z, p) => { const b = new T.Mesh(new T.BoxGeometry(w, h, d), m); b.position.set(x, y, z); p.add(b); return b; }; const cyl = (r1, r2, h, m, x, y, z, p, n = 12) => { const b = new T.Mesh(new T.CylinderGeometry(r1, r2, h, n), m); b.position.set(x, y, z); p.add(b); return b; }; const sph = (r, m, x, y, z, p, n = 12) => { const b = new T.Mesh(new T.SphereGeometry(r, n, Math.max(6, n - 4)), m); b.position.set(x, y, z); p.add(b); return b; };
const SPECIES = [
  { id: 'orb', n: 'Garden orb weaver', sz: 1.0, col: 0xa8763e, col2: 0xe0b878, legs: 'banded', abd: 1.4, fact: 'Builds a new wheel-shaped web almost every night and eats the old one to recycle the silk. Catches mosquitoes, flies and gnats by the hundreds. Harmless to people.', eat: 'flies, mosquitoes, moths', help: 'free pest control for your garden', where: 'gardens, porches, fences' },
  { id: 'jump', n: 'Jumping spider', sz: 0.35, col: 0x1b1b1b, col2: 0x38f0ff, legs: 'fuzzy', abd: 0.9, fact: 'Eight eyes, two of them huge, and better vision than most insects. It jumps 50 times its body length and tilts its head to look at you. The friendliest spider there is.', eat: 'flies, aphids, small bugs', help: 'eats garden pests, does not spin webs on your stuff', where: 'sunny walls, windowsills' },
  { id: 'wolf', n: 'Wolf spider', sz: 0.9, col: 0x5a4632, col2: 0x8a7050, legs: 'thick', abd: 1.0, fact: 'Does not build a web. She hunts on foot and carries her egg sac, then carries all her babies on her back. Eyes shine green in a flashlight at night.', eat: 'crickets, roaches, beetles', help: 'patrols lawns and basements for pests', where: 'grass, leaf litter, basements' },
  { id: 'tarantula', n: 'Tarantula', sz: 2.4, col: 0x2a1f1a, col2: 0xd98a3a, legs: 'hairy', abd: 1.3, fact: 'Big, slow, and gentle. Lives 20+ years. Its bite is milder than a bee sting and it would much rather walk away. Popular pet because it is calm.', eat: 'crickets, beetles, the occasional small lizard', help: 'keeps insect populations in balance', where: 'deserts, burrows' },
  { id: 'daddy', n: 'Cellar spider (daddy long-legs)', sz: 0.6, col: 0xc9b89a, col2: 0xe8dcc0, legs: 'thread', abd: 0.7, fact: 'Those impossibly long legs. Shakes its web wildly when bothered to become a blur. The myth about super-venom is false: it is harmless.', eat: 'other spiders, mosquitoes', help: 'eats the spiders you actually mind', where: 'ceilings, cellars, garages' },
  { id: 'peacock', n: 'Peacock jumping spider', sz: 0.25, col: 0x0b1a3a, col2: 0xff4fd8, legs: 'fuzzy', abd: 0.9, fact: 'Smaller than a grain of rice, with a flap of blazing color it raises and dances with. One of the most beautiful animals on Earth. From Australia.', eat: 'tiny insects', help: 'pollinator-friendly pest control', where: 'Australian scrub' },
  { id: 'golden', n: 'Golden silk orb weaver', sz: 1.6, col: 0x3a3a2a, col2: 0xffd23f, legs: 'banded', abd: 1.8, fact: 'Her web is golden in the sun and strong enough to catch small birds, though she lets them go. Silk so tough people have woven cloth from it.', eat: 'large flying insects', help: 'one web can clear a yard of flies', where: 'warm forests, Florida, the tropics' },
  { id: 'crab', n: 'Flower crab spider', sz: 0.4, col: 0xfff0a0, col2: 0xffffff, legs: 'wide', abd: 1.0, fact: 'Sits inside flowers and changes color, white to yellow, to match them. Walks sideways like a crab. An ambush hunter with patience.', eat: 'bees, flies that visit flowers', help: 'keeps flower pests down', where: 'daisies, goldenrod' },
  { id: 'baby', n: 'Spiderlings (babies)', sz: 0.12, col: 0xa8763e, col2: 0xe0b878, legs: 'thin', abd: 1.0, fact: 'Hundreds hatch at once, then "balloon": they let out a thread of silk and ride the wind for miles. That is how spiders get to new islands.', eat: 'tiny midges', help: 'future pest control', where: 'everywhere' }
];
function makeSpider(sp, scale, seed) { const r = (k) => Math.abs(Math.sin(seed * 12.9898 + k * 78.233) * 43758.5453) % 1; const g = new T.Group(); const s = scale; const bodyM = new T.MeshStandardMaterial({ color: sp.col, roughness: sp.legs === 'hairy' || sp.legs === 'fuzzy' ? 0.95 : 0.6, metalness: 0.05 }); const abdM = new T.MeshStandardMaterial({ color: sp.col2, roughness: 0.7 }); const ceph = sph(0.22 * s, bodyM, 0, 0.22 * s, 0.18 * s, g, 10); ceph.scale.set(1, 0.8, 1.1); const abd = sph(0.3 * s * sp.abd, abdM, 0, 0.26 * s, -0.25 * s * sp.abd, g, 12); abd.scale.set(0.9, 0.85, 1.25); if (sp.id === 'orb' || sp.id === 'golden') { for (let i = 0; i < 5; i++) { const spot = sph(0.05 * s, M(0xf8e8c0), (i % 2 ? 0.1 : -0.1) * s, 0.5 * s * sp.abd, (-0.15 - i * 0.07) * s * sp.abd, g, 6); } } if (sp.id === 'peacock') { const flap = new T.Mesh(new T.CircleGeometry(0.34 * s, 16), new T.MeshStandardMaterial({ color: 0xff4fd8, emissive: 0xff4fd8, emissiveIntensity: 0.5, side: T.DoubleSide })); flap.position.set(0, 0.45 * s, -0.3 * s); flap.rotation.x = -0.4; g.add(flap); g.userData.flap = flap; } for (const sx of [-1, 1]) { const eye = sph((sp.id === 'jump' || sp.id === 'peacock' ? 0.07 : 0.035) * s, M(0x111111, { metalness: 0.6, roughness: 0.2 }), sx * 0.09 * s, 0.3 * s, 0.36 * s, g, 6); if (sp.id === 'jump' || sp.id === 'peacock') sph(0.025 * s, M(0xffffff), sx * 0.09 * s, 0.32 * s, 0.42 * s, g, 5); } for (const sx of [-1, 1]) { const fang = cyl(0.015 * s, 0.03 * s, 0.1 * s, M(0x111111), sx * 0.05 * s, 0.14 * s, 0.36 * s, g, 5); fang.rotation.x = 0.6; }
  const legs = []; const thick = { banded: 0.035, fuzzy: 0.05, thick: 0.05, hairy: 0.07, thread: 0.012, wide: 0.04, thin: 0.015 }[sp.legs] * s; for (let i = 0; i < 4; i++) for (const sx of [-1, 1]) { const L = new T.Group(); const a = (-0.9 + i * 0.6) * (sp.legs === 'wide' && i < 2 ? 1.6 : 1); L.position.set(sx * 0.14 * s, 0.22 * s, (0.2 - i * 0.14) * s); L.rotation.y = -a * sx; g.add(L); const len = (sp.legs === 'thread' ? 1.2 : sp.legs === 'wide' && i < 2 ? 0.9 : 0.6) * s * (0.9 + r(i) * 0.2); const seg1 = cyl(thick, thick * 0.8, len, bodyM, 0, 0, 0, L, 6); seg1.rotation.z = sx * 1.1; seg1.position.set(sx * Math.cos(1.1) * len / 2, Math.sin(1.1) * len / 2 * 0.8, 0); const knee = new T.Group(); knee.position.set(sx * Math.cos(1.1) * len, Math.sin(1.1) * len * 0.8, 0); L.add(knee); const seg2 = cyl(thick * 0.8, thick * 0.4, len, i % 2 && sp.legs === 'banded' ? abdM : bodyM, 0, 0, 0, knee, 6); seg2.rotation.z = -sx * 0.9; seg2.position.set(sx * Math.cos(0.9) * len / 2 * 0.9, -Math.sin(0.9) * len / 2, 0); if (sp.legs === 'hairy' || sp.legs === 'fuzzy') for (let h = 0; h < 4; h++) { const hair = cyl(0.004 * s, 0.004 * s, 0.1 * s, bodyM, (h - 1.5) * 0.05 * s, 0, 0, seg1, 3); hair.rotation.z = 1.2; } legs.push({ L, knee, sx, i, ph: r(i + 9) * 6 }); } g.userData.legs = legs; g.userData.sp = sp; g.userData.seed = seed; return g; }
export function initFun2(app, ctx) { const { S, SPOTS, toast } = ctx; const addI = (x, z, r, label, fn) => app.addInteractable && app.addInteractable(x, z, r, label, fn); const popup = (t, h, acts) => app.popup ? app.popup(t, h, acts) : toast(t);
  /* ---------------- Spider World ---------------- */
  const SW = { x: -140, z: -320, r: 20 }; { const g = new T.Group(); g.position.set(SW.x, 0, SW.z); S.add(g); const R = SW.r; const floor = new T.Mesh(new T.CircleGeometry(R, 40), M(0x2b2b33, { roughness: 0.9 })); floor.rotation.x = -Math.PI / 2; floor.position.y = 0.06; g.add(floor); const domeM = new T.MeshPhysicalMaterial({ color: 0x9fd8ff, transparent: true, opacity: 0.14, roughness: 0.05, side: T.BackSide }); const dome = new T.Mesh(new T.SphereGeometry(R, 32, 16, 0, Math.PI * 2, 0, Math.PI / 2), domeM); dome.position.y = 0.2; g.add(dome); const ribs = new T.LineSegments(new T.EdgesGeometry(new T.SphereGeometry(R + 0.05, 16, 8, 0, Math.PI * 2, 0, Math.PI / 2)), new T.LineBasicMaterial({ color: 0xb08cff, transparent: true, opacity: 0.5 })); ribs.position.y = 0.2; g.add(ribs); for (let i = 0; i < 10; i++) { const a = i / 10 * 6.283; cyl(0.25, 0.3, 3.4, M(0x1e1b2e), Math.cos(a) * R, 1.7, Math.sin(a) * R, g, 8); }
    // webs: radial + spiral line webs hung between the ribs, plus dew sparkle
    const webM = new T.LineBasicMaterial({ color: 0xffffff, transparent: true, opacity: 0.35 }); const mkWeb = (cx, cy, cz, rad, nx, ny, nz) => { const pts = []; const spokes = 14; const q = new T.Quaternion().setFromUnitVectors(new T.Vector3(0, 0, 1), new T.Vector3(nx, ny, nz).normalize()); const P = (u, rr) => new T.Vector3(Math.cos(u) * rr, Math.sin(u) * rr, 0).applyQuaternion(q).add(new T.Vector3(cx, cy, cz)); for (let i = 0; i < spokes; i++) { const u = i / spokes * 6.283; pts.push(P(u, 0), P(u, rad)); } for (let k = 1; k <= 7; k++) { const rr = rad * k / 7; for (let i = 0; i < spokes; i++) { pts.push(P(i / spokes * 6.283, rr * (0.96 + 0.04 * Math.sin(i))), P((i + 1) / spokes * 6.283, rr * (0.96 + 0.04 * Math.sin(i + 1)))); } } const geo = new T.BufferGeometry().setFromPoints(pts); const web = new T.LineSegments(geo, webM); g.add(web); return web; }; const webs = []; for (let i = 0; i < 9; i++) { const a = i / 9 * 6.283 + 0.2; const rr = R - 2.5; webs.push(mkWeb(Math.cos(a) * rr, 3.5 + (i % 3) * 2.2, Math.sin(a) * rr, 2.2 + (i % 2) * 1.2, -Math.cos(a), 0.2, -Math.sin(a))); } webs.push(mkWeb(0, 9.5, 0, 5.5, 0, -1, 0)); webs.push(mkWeb(6, 2.2, -6, 1.6, 0.6, 0.4, 0.7)); const dew = new T.Points(new T.BufferGeometry().setAttribute('position', new T.Float32BufferAttribute(Array.from({ length: 240 * 3 }, (_, k) => k % 3 === 1 ? 1 + Math.random() * 10 : (Math.random() - 0.5) * (R * 1.6)), 3)), new T.PointsMaterial({ color: 0xffffff, size: 0.06, transparent: true, opacity: 0.8 })); g.add(dew);
    // the spiders: every one a different species, size and seed; they walk the floor, the webs, the dome
    const spiders = []; let n = 0; SPECIES.forEach((sp, si) => { const count = sp.id === 'baby' ? (MOB ? 10 : 22) : sp.id === 'tarantula' ? 2 : 3; for (let k = 0; k < count; k++) { const seed = si * 10 + k; const scale = sp.sz * (0.75 + Math.abs(Math.sin(seed * 3.7)) * 0.6); const m = makeSpider(sp, scale, seed); const a = Math.random() * 6.283, rr = Math.random() * (R - 3); const onWeb = sp.id !== 'wolf' && sp.id !== 'tarantula' && sp.id !== 'jump' && Math.random() < 0.5; const y = onWeb ? 2 + Math.random() * 7 : 0.08; m.position.set(Math.cos(a) * rr, y, Math.sin(a) * rr); g.add(m); const rec = { m, sp, a: Math.random() * 6.283, v: (sp.id === 'jump' ? 1.6 : sp.id === 'tarantula' ? 0.25 : sp.id === 'baby' ? 0.6 : 0.5) * (0.7 + Math.random() * 0.6), onWeb, pause: Math.random() * 3, jump: 0, scale }; spiders.push(rec); app.addHotspot && app.addHotspot(m, { title: '🕷️ ' + sp.n, html: `<p>${sp.fact}</p><p><b>Eats:</b> ${sp.eat}<br><b>Helps by:</b> ${sp.help}<br><b>Lives in:</b> ${sp.where}<br><b>This one:</b> ${scale < sp.sz * 0.95 ? 'a young one' : scale > sp.sz * 1.2 ? 'a big old girl' : 'adult'}, about ${(scale * 4).toFixed(1)} in across (shown ${Math.round(scale / sp.sz * 100)}% of typical)</p><p class="aou-note">Stephany says: spiders are not scary. They eat the things that bite you, and most would rather hide than meet you. 🕷️💛</p>`, actions: [{ label: '🕷️ Next spider fact', fn: () => toast(pick(['Spiders are not insects: eight legs, two body parts, no antennae.', 'A single house spider can eat 2,000 insects a year.', 'Spider silk is stronger than steel by weight.', 'Most spider "bites" people blame are actually other bugs.', 'Spiders are everywhere people are, and almost never a danger.', 'Jumping spiders can see in color, including ultraviolet.']), 5000) }] }); n++; } });
    // orb-weaver photo on the wall + Stephany's plaque
    const photoM = new T.MeshBasicMaterial({ color: 0xffffff }); new T.TextureLoader().load('/images/orb-weaver.webp', (tx) => { tx.colorSpace = T.SRGBColorSpace; photoM.map = tx; photoM.needsUpdate = true; }); const frame = box(4.4, 5.8, 0.2, M(0x1e1b2e), 0, 4, -R + 1.4, g); const photo = new T.Mesh(new T.PlaneGeometry(4, 5.4), photoM); photo.position.set(0, 4, -R + 1.52); g.add(photo); const cap = new T.Mesh(new T.PlaneGeometry(4.4, 0.8), new T.MeshBasicMaterial({ map: makeTextTexture(['A real orb weaver · photo by Stephany'], { w: 1024, h: 180, bg: 'rgba(0,0,0,0)', fg: '#fff', accent: '#b08cff', font: 'bold 60px Poppins, Arial' }), transparent: true })); cap.position.set(0, 0.8, -R + 1.52); g.add(cap); const plaque = new T.Mesh(new T.PlaneGeometry(8, 3.2), new T.MeshBasicMaterial({ map: makeTextTexture(['🕷️ SPIDER WORLD', "Stephany's room · they are not scary", 'they eat what bites you · tap any spider'], { w: 1400, h: 560, bg: 'rgba(20,10,40,0.85)', fg: '#fff', accent: '#b08cff', font: 'bold 76px Poppins, Arial' }), transparent: true })); plaque.position.set(0, 7.6, -R + 1.6); g.add(plaque); const sign = makeSprite("🕷️ SPIDER WORLD · Stephany's room · tap the spiders", { scale: 7, accent: '#b08cff' }); sign.position.set(0, R + 3, 0); g.add(sign);
    // a quiz board
    const QUIZ = [['Which spider has the best eyesight?', ['Jumping spider', 'Tarantula', 'Cellar spider'], 0], ['Which one does NOT build a web?', ['Orb weaver', 'Wolf spider', 'Golden silk orb weaver'], 1], ['How do baby spiders travel?', ['They swim', 'They ride the wind on silk', 'They hitch on birds'], 1], ['Spider silk, by weight, is stronger than…', ['Steel', 'Rope', 'Nothing'], 0], ['How many legs does a spider have?', ['6', '8', '10'], 1]]; let qi = 0, qs = 0; const quiz = () => { const [q, opts, ans] = QUIZ[qi % QUIZ.length]; popup('🕷️ Spider quiz ' + (qi % QUIZ.length + 1) + '/' + QUIZ.length, '<p>' + q + '</p>', opts.map((o, i) => ({ label: o, primary: i === 0, fn: () => { if (i === ans) { qs++; app.celebrate && app.celebrate('🕷️'); toast('✅ Right! ' + qs + ' correct.', 1500); } else toast('❌ Nope. ' + opts[ans] + '.', 2200); qi++; if (qi % QUIZ.length === 0) { toast('🏆 Quiz done: ' + qs + '/' + QUIZ.length + '. Stephany is proud.', 4000); qs = 0; } else setTimeout(quiz, 900); } }))); }; addI(SW.x + 8, SW.z - R + 3, 4, '🧠 Spider quiz (5 questions)', quiz); addI(SW.x, SW.z - R + 4, 4, '🖼️ The orb weaver photo + Stephany\'s note', () => popup('🕷️ Stephany\'s note', '<p>I love spiders. They are not the monsters people make them. They eat mosquitoes, flies, roaches and the bugs that actually hurt you, they keep gardens alive, and almost none can harm a person. Look at one up close some day. She is just working.</p><p><b>Quick rules:</b> leave her be, move her with a cup and paper if you must, never spray. 💛</p>', [{ label: '🕷️ Meet the spiders', primary: true }]));
    app.addPlace && app.addPlace({ id: 'spider-world', name: "🕷️ Spider World · Stephany's room", icon: '🕷️', x: SW.x, z: SW.z + R + 4, cat: 'Outside · the island', keys: 'spider spiders web stephany tarantula orb weaver jumping educational', say: 'A web-covered dome full of real-looking spiders, every one unique. Tap them. They are not scary.' }); app.addObstacle && app.addObstacle(SW.x, SW.z - R + 1.4, 2.2);
    app.onUpdate((dt, t) => { const P = app.player.position; const d = Math.hypot(P.x - SW.x, P.z - SW.z); if (d > 120) return; for (const s of spiders) { const m = s.m; if (s.pause > 0) { s.pause -= dt; if (s.sp.id === 'jump' && s.pause < 0.1 && Math.random() < 0.3) s.jump = 1; } else { if (Math.random() < dt * 0.4) s.a += (Math.random() - 0.5) * 2; const nx = m.position.x + Math.sin(s.a) * s.v * dt, nz = m.position.z + Math.cos(s.a) * s.v * dt; if (Math.hypot(nx, nz) < R - 2.5) { m.position.x = nx; m.position.z = nz; } else s.a += Math.PI; m.rotation.y = s.a; if (Math.random() < dt * 0.3) s.pause = 0.5 + Math.random() * 2.5; const walk = t * 14 * s.v; for (const L of m.userData.legs) { L.knee.rotation.z = Math.sin(walk + L.ph + L.i * 1.5) * 0.35; L.L.rotation.x = Math.sin(walk + L.ph + L.i * 1.5) * 0.25 * L.sx; } } if (s.jump > 0) { s.jump -= dt * 2.5; m.position.y = (s.onWeb ? m.position.y : 0.08) + Math.sin(Math.max(0, s.jump) * Math.PI) * 0.8; } if (m.userData.flap && Math.hypot(P.x - (SW.x + m.position.x), P.z - (SW.z + m.position.z)) < 4) { m.userData.flap.rotation.x = -1.3 + Math.sin(t * 8) * 0.2; m.userData.flap.scale.setScalar(1 + Math.sin(t * 6) * 0.1); } } dew.rotation.y = t * 0.01; }); }
  /* ---------------- the globe portal ---------------- */
  const GLOBE_DEST = [['🌍 allofus.one · the world', 'https://allofus.one/', 'go'], ['🏬 Inside the mall', '/mall/', 'go'], ['🎨 One Sky Gallery', '/mall/?to=gallery', 'go'], ['🏖️ Beach Cove 360', 'beach', 'tp'], ['🌊 Lake Harmony boats', 'lake', 'tp'], ['🛍️ 360 Showroom', [70, 150 + 18], 'tp'], ['🕷️ Spider World', [SW.x, SW.z + SW.r + 4], 'tp'], ['🦁 Zoo', 'zoo', 'tp'], ['🏔️ Lakeside Wilds', 'wilds', 'tp'], ['🕹️ Games · allofus arcade', 'https://allofus.one/arcade/', 'go'], ['🪐 The VR Galaxy', 'https://thevrgalaxy.com/', 'go'], ['✈️ VR Flying Simulator', 'https://vrflyingsimulator.com/', 'go']];
  const tpTo = (dest) => { let x, z; if (Array.isArray(dest)) [x, z] = dest; else { const sp = SPOTS[dest]; if (!sp) return; x = sp.x; z = sp.z + (sp.r ? sp.r * 0.6 : 10); } const jump = () => { app.player.position.set(x, 0, z); app.walkTarget = null; app.level = 0; if (app.ride && app.ride.stand) app.ride = null; }; if (app.fade) { app.fade.classList.add('on'); app.fade.textContent = '✨ On the way'; setTimeout(() => { jump(); setTimeout(() => app.fade.classList.remove('on'), 250); }, 380); } else jump(); };
  const globePortal = () => { const html = `<div class="globe-spin" style="position:relative;height:120px;display:flex;align-items:center;justify-content:center;margin:4px 0 8px"><div id="gp-ball" style="width:110px;height:110px;border-radius:50%;background:radial-gradient(circle at 35% 35%,#7cf8ff,#2f6bff 55%,#0b1a5a 90%);box-shadow:0 0 40px #38f0ff88, inset -18px -14px 30px #00000088;animation:gpspin 6s linear infinite"></div><style>@keyframes gpspin{from{background-position:0 0;transform:rotate(0deg)}to{transform:rotate(360deg)}}</style></div><p style="margin:0 0 8px">Spin it, pick a pin, go.</p><div class="aou-chips mp-row" style="display:flex;flex-wrap:wrap;gap:6px">${GLOBE_DEST.map(([n], i) => `<button class="mp-btn" data-gd="${i}">${n}</button>`).join('')}</div>`; const m = ctx.modal ? ctx.modal('🌍 The globe · where to?', html) : null; (m || document).querySelectorAll('[data-gd]').forEach(b => b.onclick = () => { const [n, dest, kind] = GLOBE_DEST[+b.dataset.gd]; ctx.close && ctx.close(); if (kind === 'go') { if (app.go) app.go(dest, n); else location.href = dest; } else tpTo(dest); }); if (!m) { const [n, dest, kind] = GLOBE_DEST[0]; if (app.go) app.go(dest, n); } };
  const patchGlobe = () => { const it = (app.interactables || []).find(i => /Spin the hologram/.test(i.label || '')); if (it) { it.label = '🌍 Spin the globe · pick where to go'; it.fn = globePortal; it.r = Math.max(it.r || 2.4, 4); return true; } return false; }; if (!patchGlobe()) { let tries = 0; const iv = setInterval(() => { if (patchGlobe() || ++tries > 120) clearInterval(iv); }, 2000); }
  /* ---------------- quick ports + beach shortcut ---------------- */
  ctx.ports = { beach: () => tpTo('beach'), spiders: () => tpTo([SW.x, SW.z + SW.r + 4]), globe: globePortal };
  /* ---------------- shopping-cart modes ---------------- */
  ctx.cartModes = () => { const av = app.avatar; if (!av || av.userData.kind !== 'cart') { toast('🛒 Pick the Shopping Cart character first (👤 → Shopping Cart).', 3000); return; } const html = `<p>Your cart, your rules.</p><div class="mp-row" style="display:flex;flex-wrap:wrap;gap:6px"><button class="mp-btn" data-cm="neon">💡 Neon mode</button><button class="mp-btn" data-cm="giant">🛞 Giant tires</button><button class="mp-btn" data-cm="color">🎨 New color</button><button class="mp-btn" data-cm="gold">🥇 Gold plated</button><button class="mp-btn" data-cm="reset">↺ Reset</button></div>`; const m = ctx.modal ? ctx.modal('🛒 Cart modes', html) : null; (m || document).querySelectorAll('[data-cm]').forEach(b => b.onclick = () => { const k = b.dataset.cm; const wheels = av.userData.wheels || []; if (k === 'giant') { wheels.forEach(w => w.scale.setScalar(w.scale.x > 1.5 ? 1 : 2.6)); toast('🛞 Monster cart.'); } else if (k === 'neon') { av.traverse(o => { if (o.isMesh && o.material && o.material.emissive) { o.material = o.material.clone(); o.material.emissive.setHex(0x38f0ff); o.material.emissiveIntensity = o.material.emissiveIntensity > 0.5 ? 0 : 0.9; } }); toast('💡 Neon cart.'); } else if (k === 'color' || k === 'gold') { const c = k === 'gold' ? 0xffd23f : [0xff4f79, 0x7cff6b, 0xb388ff, 0xff8a3d, 0x38f0ff][Math.floor(Math.random() * 5)]; av.traverse(o => { if (o.isMesh && o.material && o.material.metalness > 0.7 && o.geometry.type === 'BoxGeometry') { o.material = o.material.clone(); o.material.color.setHex(c); if (k === 'gold') { o.material.metalness = 1; o.material.roughness = 0.15; } } }); toast(k === 'gold' ? '🥇 Gold plated. Fancy.' : '🎨 Fresh paint.'); } else if (k === 'reset') { app.setAvatar && app.setAvatar(app.avatarSpec || {}); toast('↺ Back to stock.'); } }); };
  /* ---------------- coaster: FOV punch on the fast parts ---------------- */
  let lastP = null, lastT = 0; app.onUpdate((dt, t) => { if (!app.ride || app.ride.stand || !app.camera) { if (lastP && app.camera.fov !== 70) { app.camera.fov += (70 - app.camera.fov) * 0.2; app.camera.updateProjectionMatrix(); if (Math.abs(app.camera.fov - 70) < 0.2) { app.camera.fov = 70; app.camera.updateProjectionMatrix(); lastP = null; } } return; } const P = app.player.position; if (lastP && t - lastT > 0.05) { const sp = lastP.distanceTo(P) / (t - lastT); const want = 70 + Math.min(18, Math.max(0, sp - 6) * 1.2); app.camera.fov += (want - app.camera.fov) * 0.15; app.camera.updateProjectionMatrix(); } if (!lastP) lastP = new T.Vector3(); if (t - lastT > 0.05) { lastP.copy(P); lastT = t; } });
  return ctx;
}
