/* LIFEboard in VR (Oct 2026): a wall-mounted control panel you tap with the laser. Reads and writes the same lifeboards.data the
   flat board and the 3D board use (UI.LB / UI.saveLB → DB adapter; guests fall back to localStorage). Tap-only: no text entry in a
   headset. Widgets: Today (affirmation + top 3 ticks), Habits (tick), Goals (progress, tap to advance), Life wheel (SVG → texture),
   Reminders (tick), Focus timer (start/stop), Hugs (sent / got). S/M/L per widget via its corner button; layout persisted to
   lifeboards.data.vrdash. Opens from the VR menu (Me → LIFEboard panel). World VR Mall port: data comes from window.WVM.UI (wvm-plus.js); there is no office panel here. */
import { THREE } from './wvm-engine.js';
import { AFFIRMATIONS } from './wvm-lifetools.js';
const T = THREE; const NEON = 0x38f0ff, GOLD = 0xffd23f, MINT = 0x7cff6b, ROSE = 0xff4f79;
const today = () => new Date().toISOString().slice(0, 10);
const uid = () => Math.random().toString(36).slice(2, 10);
const ensure = (lb) => { lb.wheel = lb.wheel || { Goals: 6, Social: 5, Wellness: 6, Work: 7, Giving: 4, Create: 5 }; lb.goals = lb.goals || []; lb.habits = lb.habits || []; lb.reminders = lb.reminders || []; lb.focus = lb.focus || []; lb.hugs = lb.hugs || { sent: 0, got: 0 }; lb.top3 = lb.top3 || { d: '', items: ['', '', ''] }; if (lb.top3.d !== today()) lb.top3 = { d: today(), items: (lb.top3.items || ['', '', '']), done: [false, false, false] }; lb.top3.done = lb.top3.done || [false, false, false]; lb.aff = lb.aff || { bag: [], d: '', i: -1, pinned: '' }; lb.vrdash = lb.vrdash || { sizes: {}, order: [] }; return lb; };
const affirmation = (lb) => { const A = lb.aff; if (A.d !== today() || A.i < 0) { if (!A.bag.length) A.bag = [...AFFIRMATIONS.keys()].sort(() => Math.random() - 0.5); A.i = A.bag.shift(); A.d = today(); } return AFFIRMATIONS[A.i % AFFIRMATIONS.length]; };
const WIDGETS = ['today', 'habits', 'goals', 'wheel', 'reminders', 'focus', 'hugs'];
const SIZES = { S: 0.62, M: 0.82, L: 1.04 };
const FOCUS = { end: 0, mins: 25, label: 'Deep work' };
export function initLifeVR(app, X, h) {
  const { makeTextTexture, btnFace, toast } = h; const haptic = h.haptic || (() => { });
  const getUI = () => (h.getUI && h.getUI()) || h.UI || (window.WVM && window.WVM.UI) || (window.AOU && window.AOU.UI) || null;
  const LB = () => { const UI = getUI(); let d = null; try { d = UI && UI.LB ? UI.LB() : null; } catch (e) { } if (!d) { try { d = JSON.parse(localStorage.getItem('aou_lb_guest') || 'null'); } catch (e) { } } if (!d) d = {}; return ensure(d); };
  const save = (lb) => { const UI = getUI(); try { if (UI && UI.saveLB) { UI.saveLB(lb); return; } } catch (e) { } try { localStorage.setItem('aou_lb_guest', JSON.stringify(lb)); } catch (e) { } };
  const G = new T.Group(); G.visible = false; G.userData.noCull = true; G.userData.noOcclude = true; app.scene.add(G);
  const items = []; const texCache = new Map();
  const face = (label, accent, on, w = 1024, h2 = 200, font = 68) => { const hex = '#' + accent.toString(16).padStart(6, '0'); const k = label + '|' + hex + '|' + (on ? 1 : 0) + '|' + w + 'x' + h2; let t = texCache.get(k); if (!t) { t = btnFace(label, { w, h: h2, bg: on ? hex : 'rgba(8,20,50,0.94)', fg: on ? '#04122a' : '#fff', accent: on ? '#04122a' : hex, font: 'bold ' + font + 'px Poppins, Arial', radius: 50, border: hex, glow: false, on }); texCache.set(k, t); if (texCache.size > 260) { const f = texCache.keys().next().value; try { texCache.get(f).dispose(); } catch (e) { } texCache.delete(f); } } return t; };
  const plane = (w, hh, tex, o = {}) => { const m = new T.Mesh(new T.PlaneGeometry(w, hh), new T.MeshBasicMaterial({ map: tex, transparent: true, depthTest: false, depthWrite: false, opacity: o.opacity === undefined ? 1 : o.opacity })); m.renderOrder = 998; m.frustumCulled = false; m.userData.isSign = false; G.add(m); items.push(m); if (o.fn) { m.userData.vrfn = o.fn; m.userData.label = o.label || ''; X.extraTargets.push(m); } return m; };
  const clear = () => { for (const m of items) { G.remove(m); try { m.geometry.dispose(); } catch (e) { } const i = X.extraTargets.indexOf(m); if (i >= 0) X.extraTargets.splice(i, 1); } items.length = 0; };
  /* the life wheel: an SVG drawn like the flat board's, rasterized to a texture */
  let wheelTex = null, wheelKey = '';
  const wheelTexture = (lb) => { const keys = Object.keys(lb.wheel); const key = keys.map(k => k + lb.wheel[k]).join(','); if (wheelTex && wheelKey === key) return wheelTex; wheelKey = key; const n = keys.length, cx = 150, cy = 150, r = 112; const cols = ['#7c3aed', '#2563eb', '#16a34a', '#0891b2', '#e11d48', '#ea580c', '#38f0ff', '#ffd23f'];
    const p = (a, R2) => (cx + Math.cos(a) * R2).toFixed(1) + ',' + (cy + Math.sin(a) * R2).toFixed(1);
    const seg = keys.map((k, i) => { const a0 = i / n * Math.PI * 2 - Math.PI / 2, a1 = (i + 1) / n * Math.PI * 2 - Math.PI / 2; const rr = r * lb.wheel[k] / 10; const am = (a0 + a1) / 2; return `<path d="M${cx},${cy} L${p(a0, r)} A${r},${r} 0 0 1 ${p(a1, r)} Z" fill="${cols[i % cols.length]}" opacity=".18"/><path d="M${cx},${cy} L${p(a0, rr)} A${rr},${rr} 0 0 1 ${p(a1, rr)} Z" fill="${cols[i % cols.length]}" opacity=".9"/><text x="${(cx + Math.cos(am) * (r + 22)).toFixed(0)}" y="${(cy + Math.sin(am) * (r + 22) + 5).toFixed(0)}" text-anchor="middle" font-size="13" font-weight="700" fill="#ffffff" font-family="Poppins,Arial">${k} ${lb.wheel[k]}</text>`; }).join('');
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 300" width="600" height="600"><rect width="300" height="300" rx="24" fill="rgba(8,20,50,0.94)"/><rect x="3" y="3" width="294" height="294" rx="22" fill="none" stroke="#38f0ff" stroke-width="3"/>${seg}<circle cx="${cx}" cy="${cy}" r="16" fill="#fff"/></svg>`;
    const c = document.createElement('canvas'); c.width = c.height = 600; const tex = new T.CanvasTexture(c); tex.colorSpace = T.SRGBColorSpace; const im = new Image(); im.onload = () => { try { c.getContext('2d').drawImage(im, 0, 0, 600, 600); tex.needsUpdate = true; } catch (e) { } }; im.src = 'data:image/svg+xml;utf8,' + encodeURIComponent(svg); wheelTex = tex; return tex; };
  /* widget definitions: each returns rows [label, fn, accent, on] and an optional art {tex, aspect} */
  const streak = (h2) => { let s = 0; for (let i = 0; i < 365; i++) { const k = new Date(Date.now() - i * 86400000).toISOString().slice(0, 10); if (h2.days.includes(k)) s++; else if (i > 0) break; } return s; };
  const W = {
    today: { title: '☀️ Today', rows: (lb, rb) => { const d = today(); const aff = affirmation(lb); const rows = [['“' + aff.slice(0, 44) + (aff.length > 44 ? '…' : '') + '”', () => { lb.aff.i = -1; affirmation(lb); save(lb); rb(); }, GOLD]]; lb.top3.items.forEach((t, i) => rows.push([(lb.top3.done[i] ? '✅ ' : '🎯 ') + (t || 'Priority ' + (i + 1) + ' · set it on the Feed'), () => { lb.top3.done[i] = !lb.top3.done[i]; save(lb); haptic(0.4, 30); rb(); }, lb.top3.done[i] ? MINT : NEON, lb.top3.done[i]])); rows.push(['📅 ' + new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' }), () => { }, 0x94a3b8]); return rows; } },
    habits: { title: '🌱 Habits', rows: (lb, rb) => { const d = today(); if (!lb.habits.length) return [['No habits yet · add them on the Feed', () => { }, 0x94a3b8]]; return lb.habits.slice(0, 7).map(h2 => { const on = h2.days.includes(d); return [(on ? '✅ ' : '⬜ ') + h2.t.slice(0, 28) + ' · 🔥' + streak(h2), () => { h2.days = on ? h2.days.filter(x => x !== d) : [...new Set([...h2.days, d])]; save(lb); haptic(0.4, 30); rb(); }, on ? MINT : NEON, on]; }); } },
    goals: { title: '🎯 Goals', rows: (lb, rb) => { const n = lb.goals.length, done = lb.goals.filter(g => g.col === 'done').length, doing = lb.goals.filter(g => g.col === 'doing').length; const bar = '█'.repeat(Math.round(n ? done / n * 12 : 0)) + '░'.repeat(12 - Math.round(n ? done / n * 12 : 0)); const rows = [[bar + ' ' + (n ? Math.round(done / n * 100) : 0) + '% · ' + doing + ' doing', () => { }, GOLD]]; const order = ['dream', 'doing', 'done']; lb.goals.filter(g => g.col !== 'done').slice(0, 5).forEach(g => rows.push([(g.col === 'doing' ? '🔨 ' : '💭 ') + g.t.slice(0, 30), () => { const k = order.indexOf(g.col); g.col = order[Math.min(2, k + 1)]; save(lb); haptic(0.5, 40); if (g.col === 'done') toast('🎯 Done: ' + g.t, 2000); rb(); }, g.col === 'doing' ? MINT : NEON])); if (!n) rows.push(['Add goals on the Feed → LIFEboard', () => { }, 0x94a3b8]); return rows; } },
    wheel: { title: '🧭 Life wheel', art: (lb) => ({ tex: wheelTexture(lb), aspect: 1 }), rows: (lb, rb) => Object.keys(lb.wheel).slice(0, 6).map(k => [k + ' ' + lb.wheel[k] + '/10 · tap +1', () => { lb.wheel[k] = lb.wheel[k] >= 10 ? 1 : lb.wheel[k] + 1; save(lb); haptic(0.3, 20); rb(); }, NEON]) },
    reminders: { title: '⏰ Reminders', rows: (lb, rb) => { const list = [...lb.reminders].filter(r => !r.done).sort((a, b) => new Date(a.at) - new Date(b.at)).slice(0, 6); if (!list.length) return [['Nothing due · add reminders on the Feed', () => { }, 0x94a3b8]]; return list.map(r => [('⏰ ' + r.t).slice(0, 26) + ' · ' + new Date(r.at).toLocaleString('en-US', { weekday: 'short', hour: 'numeric', minute: '2-digit' }), () => { r.done = true; save(lb); haptic(0.5, 40); toast('✅ ' + r.t, 1500); rb(); }, NEON]); } },
    focus: { title: '⏱️ Focus timer', rows: (lb, rb) => { const running = FOCUS.end > Date.now(); const left = Math.max(0, FOCUS.end - Date.now()); const mm = Math.floor(left / 60000), ss = Math.floor(left / 1000) % 60; const days = [...Array(7)].map((_, i) => new Date(Date.now() - (6 - i) * 86400000).toISOString().slice(0, 10)); const total = lb.focus.filter(f => days.includes(f.d)).reduce((a, f) => a + (f.min || 0), 0); const rows = [[running ? '⏹ Stop · ' + mm + ':' + String(ss).padStart(2, '0') + ' left' : '▶ Start ' + FOCUS.mins + ' min · ' + FOCUS.label, () => { if (running) { const did = Math.round((FOCUS.mins * 60000 - left) / 60000); FOCUS.end = 0; if (did >= 1) { lb.focus.push({ d: today(), min: did, what: FOCUS.label }); save(lb); toast('⏱️ ' + did + ' min logged', 2000); } } else { FOCUS.end = Date.now() + FOCUS.mins * 60000; toast('⏱️ Focus: ' + FOCUS.mins + ' min. Go.', 2000); } haptic(0.6, 50); rb(); }, running ? ROSE : MINT, running]]; if (!running) rows.push(['Length: ' + FOCUS.mins + ' min · tap to change', () => { FOCUS.mins = { 25: 50, 50: 15, 15: 5, 5: 25 }[FOCUS.mins] || 25; rb(); }, NEON]); rows.push(['📊 This week: ' + total + ' min', () => { }, 0x94a3b8]); return rows; } },
    hugs: { title: '🤗 Hugs', rows: (lb, rb) => [['Sent ' + (lb.hugs.sent || 0) + ' · got ' + (lb.hugs.got || 0), () => { }, GOLD], ['🤗 Send a hug to someone near', () => { try { const api = window.AOU && window.AOU.W && window.AOU.W.api; if (api && api.moreAction) { api.moreAction('hug'); lb.hugs.sent = (lb.hugs.sent || 0) + 1; save(lb); rb(); } else toast('Hugs live on allofus.one → LIFEboard → Hugs', 2000); } catch (e) { } }, ROSE]] },
  };
  const BW = 0.74, RH = 0.062, HH = 0.08;
  let built = 0; const rebuild = () => { const lb = LB(); clear(); const sizes = lb.vrdash.sizes || {}; const order = (lb.vrdash.order && lb.vrdash.order.length ? lb.vrdash.order : WIDGETS).filter(k => W[k]);
    const cols = []; let x = 0, y = 0, colW = 0, maxH = 0; const MAXW = 2.75; const widgets = [];
    for (const key of order) { const sz = SIZES[sizes[key]] || SIZES.M; const w = BW * sz; const def = W[key]; const rows = def.rows(lb, rebuild); const art = def.art ? def.art(lb) : null; const hh = HH * sz + rows.length * RH * sz + (art ? w * art.aspect * 0.78 : 0) + 0.03; if (x + w > MAXW) { x = 0; y -= maxH + 0.05; maxH = 0; } widgets.push({ key, x, y, w, hh, sz, rows, art, def }); x += w + 0.04; maxH = Math.max(maxH, hh); }
    const totalW = Math.min(MAXW, Math.max(...widgets.map(q => q.x + q.w))), totalH = -y + maxH; const x0 = -totalW / 2, y0 = totalH / 2;
    for (const q of widgets) { const left = x0 + q.x, top = y0 + q.y; let cy = top - HH * q.sz / 2; const head = plane(q.w - 0.1 * q.sz, HH * q.sz, face(q.def.title, GOLD, false, 1200, 190, 76), { fn: () => { }, label: q.def.title }); head.position.set(left + (q.w - 0.1 * q.sz) / 2, cy, 0); const szKey = sizes[q.key] || 'M'; const sb = plane(0.09 * q.sz, HH * q.sz, face(szKey, NEON, true, 200, 200, 110), { fn: () => { const nx = { S: 'M', M: 'L', L: 'S' }[szKey]; const lb2 = LB(); lb2.vrdash.sizes = Object.assign({}, lb2.vrdash.sizes, { [q.key]: nx }); save(lb2); haptic(0.3, 20); rebuild(); }, label: 'size' }); sb.position.set(left + q.w - 0.045 * q.sz, cy, 0); cy -= HH * q.sz / 2 + 0.01;
      if (q.art) { const ah = q.w * q.art.aspect * 0.78; const a = plane(q.w * 0.78, ah, q.art.tex); a.position.set(left + q.w / 2, cy - ah / 2, 0); cy -= ah + 0.01; }
      for (const r of q.rows) { const m = plane(q.w, RH * q.sz - 0.008, face(r[0], r[2] || NEON, !!r[3]), { fn: r[1], label: r[0] }); m.position.set(left + q.w / 2, cy - RH * q.sz / 2, 0); cy -= RH * q.sz; } }
    const back = new T.Mesh(new T.PlaneGeometry(totalW + 0.12, totalH + 0.2), new T.MeshBasicMaterial({ color: 0x030818, transparent: true, opacity: 0.78, depthTest: false })); back.renderOrder = 997; back.position.z = -0.02; G.add(back); items.push(back);
    const title = plane(1.1, 0.085, makeTextTexture(['LIFEboard · tap a row · Y closes'], { w: 1400, h: 120, bg: 'rgba(0,0,0,0)', fg: '#ffd23f', accent: '#fff', font: 'bold 60px Poppins, Arial', glow: true, border: null })); title.position.set(0, totalH / 2 + 0.11, 0);
    const close = plane(0.3, 0.07, face('✕ Close', ROSE), { fn: () => api.close(), label: 'close' }); close.position.set(totalW / 2 - 0.1, totalH / 2 + 0.11, 0);
    built = app.t; };
  const _v = new T.Vector3(), _v2 = new T.Vector3();
  const api = {
    group: G, rebuild,
    open: (mount) => { rebuild(); G.visible = true; if (mount && mount.pos) { G.position.copy(mount.pos); G.rotation.set(0, mount.yaw || 0, 0); G.scale.setScalar(mount.scale || 1); } else { const cam = app.renderer.xr.getCamera(); cam.getWorldPosition(_v); cam.getWorldDirection(_v2); _v2.y = 0; if (_v2.lengthSq() < 1e-4) _v2.set(0, 0, -1); _v2.normalize().multiplyScalar(1.7 * (X.scale || 1)).add(_v); _v2.y = _v.y - 0.05 * (X.scale || 1); G.position.copy(_v2); G.lookAt(_v.x, G.position.y, _v.z); G.scale.setScalar(X.scale || 1); } haptic(0.4, 40); },
    close: () => { G.visible = false; clear(); },
    toggle: (mount) => { if (G.visible) api.close(); else api.open(mount); },
    mountOffice: () => null, /* no office panel in the mall */
  };
  /* the focus row counts down live while the panel is open */
  let lastSec = 0; h.onFrame && h.onFrame(() => { if (!G.visible || !(FOCUS.end > Date.now())) return; const s = Math.floor((FOCUS.end - Date.now()) / 1000); if (s !== lastSec && s % 10 === 0) { lastSec = s; if (app.t - built > 0.9) rebuild(); } });
  return api;
}
