/* ============================================================
   World VR Mall · fun pack (v42)
   🕹️ Arcade Annex: retro cabinet (playable Snake), the Matrix code
   fountain flowing into the floor, and the red DO NOT PUSH button
   (code fills the room from the floor up… then an anteater eats it)
   🫧 Bubble Float ride · 🐜 golden ant secret · 🪩 a code-word party
   ============================================================ */
import { THREE, makeSprite, isMobile } from './wvm-engine.js?v=45';
const T = THREE; const MOB = isMobile();
const M = (c, o = {}) => new T.MeshStandardMaterial({ color: c, roughness: 0.7, ...o });
const glyphAtlas = (() => { let tex = null; return () => { if (tex) return tex; const c = document.createElement('canvas'); c.width = c.height = 256; const q = c.getContext('2d'); q.fillStyle = '#000'; q.fillRect(0, 0, 256, 256); q.fillStyle = '#7dff9a'; q.font = 'bold 50px "Courier New", monospace'; q.textAlign = 'center'; q.textBaseline = 'middle'; const G = '01アイウエオカキク{}</>;=+$#'; for (let i = 0; i < 16; i++) { q.shadowColor = '#3cff6e'; q.shadowBlur = 10; q.fillText(G[i], (i % 4) * 64 + 32, Math.floor(i / 4) * 64 + 34); } tex = new T.CanvasTexture(c); tex.colorSpace = T.SRGBColorSpace; return tex; }; })();
const rainMat = (dir = 1, density = 26) => new T.ShaderMaterial({ uniforms: { t: { value: 0 }, atlas: { value: glyphAtlas() } }, transparent: true, depthWrite: false, side: T.DoubleSide, blending: T.AdditiveBlending,
  vertexShader: 'varying vec2 vUv; void main(){ vUv=uv; gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0); }',
  fragmentShader: `uniform float t; uniform sampler2D atlas; varying vec2 vUv; float h(vec2 p){return fract(sin(dot(p,vec2(12.9898,78.233)))*43758.5453);} void main(){ vec2 g=vec2(${density}.0, ${density}.0*1.6); vec2 c=floor(vUv*g); float sp=0.6+h(vec2(c.x,1.0))*1.8; float y=fract(vUv.y*g.y/g.y*1.0 + ${dir}.0*t*sp*0.12 + h(vec2(c.x,3.0))); float trail=pow(y,6.0); float gi=floor(h(c+floor(t*4.0+h(c)*9.0))*16.0); vec2 cell=fract(vUv*g); vec2 auv=(vec2(mod(gi,4.0),3.0-floor(gi/4.0))+cell)/4.0; float a=texture2D(atlas,auv).g; vec3 col=mix(vec3(0.1,1.0,0.4),vec3(0.85,1.0,0.9),step(0.97,y)); gl_FragColor=vec4(col*a, a*(0.15+trail*0.95)); }` });

export function initFun(app, page, P) {
  const S = app.scene; const toast = (m, ms) => app.toast(m, ms);
  /* ---------- 🕹️ the Arcade Annex (inside the mall) ---------- */
  if (page === 'mall') { const CX = -700, CZ = 1200;
    const build = () => { const g = new T.Group(); g.position.set(CX, 0, CZ); S.add(g);
      const floorM = rainMat(-1, 40); const fl = new T.Mesh(new T.CircleGeometry(24, 64), floorM); fl.rotation.x = -Math.PI / 2; fl.position.y = 0.03; g.add(fl); const base = new T.Mesh(new T.CircleGeometry(24.5, 64), M(0x020805, { roughness: 0.9 })); base.rotation.x = -Math.PI / 2; base.position.y = 0.02; g.add(base);
      const wallM = rainMat(1, 60); const wall = new T.Mesh(new T.CylinderGeometry(24, 24, 11, 64, 1, true), wallM); wall.position.y = 5.5; g.add(wall); const wallBack = new T.Mesh(new T.CylinderGeometry(24.2, 24.2, 11, 64, 1, true), M(0x010402, { side: T.BackSide })); wallBack.position.y = 5.5; g.add(wallBack); const ceil = new T.Mesh(new T.CircleGeometry(24, 48), M(0x010402, { side: T.DoubleSide })); ceil.rotation.x = Math.PI / 2; ceil.position.y = 11; g.add(ceil);
      for (let i = 0; i < 56; i++) { const a = i / 56 * Math.PI * 2; if (Math.abs(Math.sin(a)) < 0.12 && Math.cos(a) > 0) continue; app.addObstacle && app.addObstacle(CX + Math.sin(a) * 24, CZ + Math.cos(a) * 24, 1.8); }
      // the code fountain: a column of falling code that splashes into a basin and spills across the floor
      const FX = 0, FZ = -6; const colM = rainMat(1, 18); const col = new T.Mesh(new T.CylinderGeometry(1.4, 1.8, 7.5, 40, 1, true), colM); col.position.set(FX, 3.75, FZ); g.add(col); const core = new T.Mesh(new T.CylinderGeometry(0.5, 0.6, 7.5, 16), new T.MeshBasicMaterial({ color: 0x0a3a1a, transparent: true, opacity: 0.6 })); core.position.set(FX, 3.75, FZ); g.add(core);
      const basin = new T.Mesh(new T.TorusGeometry(3.4, 0.35, 12, 48), M(0x0b1f12, { metalness: 0.6, roughness: 0.3, emissive: 0x0a5a22, emissiveIntensity: 0.6 })); basin.rotation.x = Math.PI / 2; basin.position.set(FX, 0.4, FZ); g.add(basin); const pool = new T.Mesh(new T.CircleGeometry(3.3, 48), rainMat(-1, 22)); pool.rotation.x = -Math.PI / 2; pool.position.set(FX, 0.5, FZ); g.add(pool); app.addObstacle && app.addObstacle(CX + FX, CZ + FZ, 3.9);
      const ftag = makeSprite('💾 THE CODE FOUNTAIN', { scale: 3.4, accent: '#3cff6e' }); ftag.position.set(FX, 8.8, FZ); g.add(ftag);
      // the retro arcade cabinet (playable)
      const cab = new T.Group(); cab.position.set(5.5, 0, -2.5); cab.rotation.y = -0.6; g.add(cab); const wood = M(0x1b1033, { roughness: 0.6 }); const side = (sx) => { const s2 = new T.Mesh(new T.BoxGeometry(0.1, 2.2, 1.1), M(0x7c3aed, { roughness: 0.5 })); s2.position.set(sx * 0.48, 1.1, 0); cab.add(s2); }; side(-1); side(1); const body = new T.Mesh(new T.BoxGeometry(0.9, 2.2, 1.0), wood); body.position.y = 1.1; cab.add(body);
      const sc = document.createElement('canvas'); sc.width = 160; sc.height = 120; const sq = sc.getContext('2d'); const stex = new T.CanvasTexture(sc); const screen = new T.Mesh(new T.PlaneGeometry(0.72, 0.54), new T.MeshBasicMaterial({ map: stex })); screen.position.set(0, 1.6, 0.47); screen.rotation.x = -0.25; cab.add(screen);
      const marquee = new T.Mesh(new T.PlaneGeometry(0.86, 0.24), new T.MeshBasicMaterial({ map: (() => { const c = document.createElement('canvas'); c.width = 512; c.height = 140; const q = c.getContext('2d'); const gr = q.createLinearGradient(0, 0, 512, 0); gr.addColorStop(0, '#ff4fd8'); gr.addColorStop(1, '#38f0ff'); q.fillStyle = gr; q.fillRect(0, 0, 512, 140); q.fillStyle = '#fff'; q.font = 'bold 74px "Courier New", monospace'; q.textAlign = 'center'; q.fillText('CODE SNAKE', 256, 96); const t2 = new T.CanvasTexture(c); t2.colorSpace = T.SRGBColorSpace; return t2; })() })); marquee.position.set(0, 2.08, 0.51); cab.add(marquee);
      const panel = new T.Mesh(new T.BoxGeometry(0.9, 0.08, 0.42), M(0x111111)); panel.position.set(0, 1.12, 0.62); panel.rotation.x = 0.2; cab.add(panel); const stick = new T.Mesh(new T.CylinderGeometry(0.02, 0.02, 0.16, 8), M(0x222222)); stick.position.set(-0.2, 1.24, 0.62); cab.add(stick); const knob = new T.Mesh(new T.SphereGeometry(0.05, 10, 8), M(0xe11d48)); knob.position.set(-0.2, 1.32, 0.62); cab.add(knob); for (let i = 0; i < 3; i++) { const bt = new T.Mesh(new T.CylinderGeometry(0.035, 0.035, 0.03, 12), M([0xffd23f, 0x38f0ff, 0x7cff6b][i], { emissive: [0xffd23f, 0x38f0ff, 0x7cff6b][i], emissiveIntensity: 0.6 })); bt.position.set(0.05 + i * 0.1, 1.18, 0.64); cab.add(bt); }
      app.addObstacle && app.addObstacle(CX + 5.5, CZ - 2.5, 0.9); let demo = [[8, 6], [7, 6], [6, 6]], dir = [1, 0], food = [12, 3], acc = 0;
      app.onUpdate((dt, t) => { colM.uniforms.t.value = t; floorM.uniforms.t.value = t; wallM.uniforms.t.value = t * 0.8; pool.material.uniforms.t.value = t * 1.4; const P2 = app.player.position; if (Math.hypot(P2.x - CX, P2.z - CZ) > 70) return; acc += dt; if (acc < 0.12) return; acc = 0; const hd = demo[0]; if (Math.random() < 0.2) dir = [[1, 0], [-1, 0], [0, 1], [0, -1]][Math.floor(Math.random() * 4)]; if (hd[0] < food[0]) dir = [1, 0]; else if (hd[0] > food[0]) dir = [-1, 0]; else if (hd[1] < food[1]) dir = [0, 1]; else if (hd[1] > food[1]) dir = [0, -1]; const nh = [(hd[0] + dir[0] + 20) % 20, (hd[1] + dir[1] + 15) % 15]; demo.unshift(nh); if (nh[0] === food[0] && nh[1] === food[1]) food = [Math.floor(Math.random() * 20), Math.floor(Math.random() * 15)]; else demo.pop(); if (demo.length > 14) demo.length = 14; sq.fillStyle = '#031208'; sq.fillRect(0, 0, 160, 120); sq.fillStyle = '#ff4f79'; sq.fillRect(food[0] * 8, food[1] * 8, 7, 7); sq.fillStyle = '#3cff6e'; demo.forEach(([x, y]) => sq.fillRect(x * 8, y * 8, 7, 7)); sq.fillStyle = 'rgba(255,255,255,.75)'; sq.font = 'bold 10px monospace'; sq.fillText((t % 2 < 1) ? 'INSERT COIN · TAP' : 'HI ' + (+localStorage.getItem('wvm_snake_hi') || 0), 6, 116); stex.needsUpdate = true; });
      const play = () => snakeGame(app); app.addHotspot && app.addHotspot(cab, { fn: play }); app.addInteractable && app.addInteractable(CX + 5.5 + Math.sin(-0.6) * 1.6, CZ - 2.5 + Math.cos(-0.6) * 1.6, 2.4, '🕹️ Play Code Snake', play);
      // the red button
      const btnG = new T.Group(); btnG.position.set(-4.5, 0, -1.5); g.add(btnG); const ped = new T.Mesh(new T.CylinderGeometry(0.45, 0.55, 1.05, 24), M(0x1f2937, { metalness: 0.5 })); ped.position.y = 0.52; btnG.add(ped); const ring = new T.Mesh(new T.TorusGeometry(0.3, 0.05, 10, 32), M(0xffd23f, { metalness: 0.8 })); ring.rotation.x = Math.PI / 2; ring.position.y = 1.07; btnG.add(ring); const dome = new T.Mesh(new T.SphereGeometry(0.27, 24, 14, 0, Math.PI * 2, 0, Math.PI / 2), new T.MeshStandardMaterial({ color: 0xe11d2a, emissive: 0xe11d2a, emissiveIntensity: 0.9, roughness: 0.25 })); dome.position.y = 1.06; btnG.add(dome);
      const warn = makeSprite('⛔ DO NOT PUSH', { scale: 2.6, accent: '#ff2d55' }); warn.position.y = 2.3; btnG.add(warn); app.addObstacle && app.addObstacle(CX - 4.5, CZ - 1.5, 0.6);
      let busy = false; const push = () => { if (busy) { toast('…it is already happening. 😬'); return; } busy = true; dome.position.y = 1.0; setTimeout(() => { dome.position.y = 1.06; }, 300); app.buzz && app.buzz(120); toast('😳 You pushed it. Of course you did.', 2500); codeFlood(app, g, CX, CZ, () => { busy = false; }); };
      app.addHotspot && app.addHotspot(btnG, { fn: push }); app.addInteractable && app.addInteractable(CX - 4.5, CZ, 2.2, '🔴 Do NOT push the button', push);
      app.onUpdate((dt, t) => { dome.material.emissiveIntensity = 0.7 + Math.sin(t * 4) * 0.35; warn.position.y = 2.3 + Math.sin(t * 2) * 0.06; });
      // the way out
      const ex = new T.Group(); ex.position.set(0, 0, 18); g.add(ex); const er = new T.Mesh(new T.TorusGeometry(1.4, 0.12, 10, 40), new T.MeshBasicMaterial({ color: 0x3cff6e })); er.rotation.x = Math.PI / 2; er.position.y = 0.1; ex.add(er); const et = makeSprite('🚪 Back to the lobby', { scale: 2.6, accent: '#3cff6e' }); et.position.y = 2.6; ex.add(et); const goLobby = () => app.travel({ id: '_lobby', name: 'the Grand Lobby', icon: '🏬', x: 3, z: 92, keys: '', say: 'Back in the Grand Lobby.' }); app.addHotspot && app.addHotspot(ex, { fn: goLobby }); app.addInteractable && app.addInteractable(CX, CZ + 18, 2.2, '🚪 Back to the lobby', goLobby); };
    if (app.addZone) app.addZone('arcade-annex', new T.Vector3(CX, 0, CZ), 160, build); else build();
    app.addPlace && app.addPlace({ id: 'code-room', name: '🕹️ Arcade Annex · the Code Fountain + the DO NOT PUSH button', icon: '🕹️', x: CX, z: CZ + 14, yaw: Math.PI, cat: 'Fun', top: true, keys: 'arcade retro cabinet snake code matrix fountain red button do not push anteater game', say: 'Retro cabinet, the code fountain, and a red button you should definitely not push.' });
    // a teleport ring in the lobby, next to the gallery one
    const tp = new T.Group(); tp.position.set(14, 0, 106); S.add(tp); const r2 = new T.Mesh(new T.TorusGeometry(1.4, 0.12, 10, 40), new T.MeshBasicMaterial({ color: 0x3cff6e })); r2.rotation.x = Math.PI / 2; r2.position.y = 0.1; tp.add(r2); const tg2 = makeSprite('🕹️ Arcade Annex · DO NOT PUSH', { scale: 3, accent: '#3cff6e' }); tg2.position.y = 3; tp.add(tg2); const goA = () => { const p = (app.places || []).find(q => q.id === 'code-room'); if (p) app.travel(p); }; app.addHotspot && app.addHotspot(tp, { fn: goA }); app.addInteractable && app.addInteractable(14, 106, 2.2, '🕹️ Teleport: Arcade Annex', goA);
  }
  /* ---------- 🫧 Bubble Float (outside): climb into a giant soap bubble and drift over everything ---------- */
  if (page === 'outside') { const BX = -62, BZ = 168; const pad = new T.Group(); pad.position.set(BX, app.opts.groundY(BX, BZ), BZ); S.add(pad); const disc = new T.Mesh(new T.CylinderGeometry(3, 3.2, 0.3, 32), M(0xe0f2fe, { metalness: 0.3, roughness: 0.3 })); disc.position.y = 0.15; pad.add(disc);
    const bubM = new T.ShaderMaterial({ uniforms: { t: { value: 0 } }, transparent: true, depthWrite: false, side: T.DoubleSide, vertexShader: 'varying vec3 vN; varying vec3 vV; void main(){ vN=normalize(normalMatrix*normal); vec4 mv=modelViewMatrix*vec4(position,1.0); vV=normalize(-mv.xyz); gl_Position=projectionMatrix*mv; }', fragmentShader: 'uniform float t; varying vec3 vN; varying vec3 vV; void main(){ float f=1.0-abs(dot(vN,vV)); float h=fract(f*1.6+t*0.08+vN.y*0.3); vec3 c=0.5+0.5*cos(6.2831*(h+vec3(0.0,0.33,0.67))); gl_FragColor=vec4(mix(vec3(1.0),c,0.85), 0.08+pow(f,2.2)*0.75); }' });
    const bubble = new T.Mesh(new T.SphereGeometry(2.3, 40, 28), bubM); bubble.position.y = 2.6; pad.add(bubble); const sg = makeSprite('🫧 BUBBLE FLOAT · climb in', { scale: 3.6, accent: '#a5f3fc' }); sg.position.y = 6; pad.add(sg); app.addObstacle && app.addObstacle(BX, BZ, 2.6);
    app.onUpdate((dt, t) => { bubM.uniforms.t.value = t; if (!riding) { bubble.position.y = 2.6 + Math.sin(t * 1.4) * 0.15; bubble.scale.set(1 + Math.sin(t * 2.2) * 0.02, 1 - Math.sin(t * 2.2) * 0.02, 1); } });
    let riding = false; const ride = () => { if (app.ride || riding) return; riding = true; const vb = new T.Group(); S.add(vb); pad.remove(bubble); vb.add(bubble); bubble.position.set(0, 0.6, 0); const prev = app.targetDist; app.targetDist = Math.max(prev > 0.6 ? prev : 7, 7);
      const pts = [[BX, 1.4, BZ], [BX + 10, 18, BZ - 20], [-40, 46, 90], [40, 70, 40], [90, 60, -60], [0, 85, -120], [-150, 70, -40], [-230, 40, 30], [-160, 30, 150], [BX - 10, 14, BZ + 10], [BX, 1.4, BZ]]; const curve = new T.CatmullRomCurve3(pts.map(p => new T.Vector3(...p)), false, 'catmullrom', 0.4);
      app.startRide((k) => { const p = curve.getPoint(k); vb.position.copy(p); vb.position.y += 0.6; return p; }, { duration: 80, sit: false, toast: '🫧 Up you float, inside a giant soap bubble. Drag to look around.', endToast: '🫧 Pop! Soft landing.', exitLabel: '🫧 Pop the bubble (land now)', exit: new T.Vector3(BX + 4, 0, BZ + 4), lookUp: true, onEnd: () => { vb.remove(bubble); S.remove(vb); bubble.position.set(0, 2.6, 0); pad.add(bubble); riding = false; app.targetDist = prev > 0.6 ? prev : 6; app.celebrate && app.celebrate('🫧'); } }); };
    app.addHotspot && app.addHotspot(pad, { fn: ride }); app.addInteractable && app.addInteractable(BX + 3.4, BZ + 2, 3.4, '🫧 Climb into the Bubble Float', ride);
    app.addPlace && app.addPlace({ id: 'bubble', name: '🫧 Bubble Float · drift over the whole island', icon: '🫧', x: BX + 4, z: BZ + 4, cat: 'Fun', top: true, keys: 'bubble float ride fly sky soap', say: 'Climb into a giant soap bubble and drift over everything.' });
  }
  /* ---------- 🐜 the Golden Ant (a tiny secret, hard to spot) ---------- */
  { const at = page === 'outside' ? [-11, 116] : [-697, 1043]; const gm = new T.MeshStandardMaterial({ color: 0xffd23f, metalness: 1, roughness: 0.2, emissive: 0x7a5200, emissiveIntensity: 0.6 }); const ant = new T.Group(); for (const [z, r] of [[-0.05, 0.04], [0, 0.028], [0.045, 0.032]]) { const s = new T.Mesh(new T.SphereGeometry(r, 10, 8), gm); s.position.z = z; ant.add(s); } ant.position.set(at[0], 0.04, at[1]); S.add(ant); let found = false;
    app.onUpdate((dt, t) => { const a = t * 0.5; ant.position.x = at[0] + Math.cos(a) * 0.8; ant.position.z = at[1] + Math.sin(a) * 0.8; ant.rotation.y = -a; const P2 = app.player.position; if (!found && Math.hypot(P2.x - ant.position.x, P2.z - ant.position.z) < 0.9) { found = true; app.secret ? app.secret('goldant', 'The Golden Ant', '<p>You found the tiniest thing in the world: a solid-gold ant. Ants can carry 10 to 50 times their own body weight. Tip: open More → 🐜 Shrink to ant size, and come say hi at eye level.</p>') : toast('🐜 You found the Golden Ant!'); } }); }
  /* ---------- 🪩 type the old code (↑ ↑ ↓ ↓ ← → ← → B A) for a party ---------- */
  { const K = ['ArrowUp', 'ArrowUp', 'ArrowDown', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'ArrowLeft', 'ArrowRight', 'b', 'a']; let i = 0; addEventListener('keydown', (e) => { if (e.target.closest && e.target.closest('input,textarea')) return; const k = e.key.length === 1 ? e.key.toLowerCase() : e.key; i = k === K[i] ? i + 1 : (k === K[0] ? 1 : 0); if (i === K.length) { i = 0; party(app); } }); }
}
function party(app) { app.toast('🪩 CODE ACCEPTED. PARTY MODE!', 3000); app.celebrate && app.celebrate('🪩'); const h = app.hemi; const c0 = h ? h.color.getHex() : null; let t0 = app.t; const f = (dt, t) => { if (h) h.color.setHSL((t * 0.4) % 1, 0.8, 0.6); if (app.avatar) app.avatar.rotation.y += dt * 6; if (t - t0 > 15) { if (h) h.color.setHex(c0); app.updaters = app.updaters.filter(q => q !== f); app.toast('🪩 Party over. You were the best dancer there.', 3000); } }; app.onUpdate(f); }

/* the red button: code pours up from the floor until the room is full, then an anteater sniffs it all up */
function codeFlood(app, room, CX, CZ, done) {
  const S = app.scene; const N = MOB ? 1100 : 2600, R = 22.5, H = 10; const pos = new Float32Array(N * 3), seed = new Float32Array(N * 4), gi = new Float32Array(N);
  for (let i = 0; i < N; i++) { const a = Math.random() * Math.PI * 2, r = Math.sqrt(Math.random()) * R; seed[i * 4] = Math.cos(a) * r; seed[i * 4 + 1] = Math.random() * H; seed[i * 4 + 2] = Math.sin(a) * r; seed[i * 4 + 3] = Math.random() * 6.283; gi[i] = Math.floor(Math.random() * 16); pos[i * 3 + 1] = -5; }
  const geo = new T.BufferGeometry(); geo.setAttribute('position', new T.BufferAttribute(pos, 3)); geo.setAttribute('gi', new T.BufferAttribute(gi, 1));
  const mat = new T.ShaderMaterial({ uniforms: { atlas: { value: glyphAtlas() }, sz: { value: MOB ? 46 : 60 } }, transparent: true, depthWrite: false, blending: T.AdditiveBlending, vertexShader: 'attribute float gi; varying float vG; uniform float sz; void main(){ vG=gi; vec4 mv=modelViewMatrix*vec4(position,1.0); gl_PointSize=sz*(10.0/max(1.0,-mv.z)); gl_Position=projectionMatrix*mv; }', fragmentShader: 'uniform sampler2D atlas; varying float vG; void main(){ vec2 c=gl_PointCoord; c.y=1.0-c.y; vec2 uv=(vec2(mod(vG,4.0),3.0-floor(vG/4.0))+c)/4.0; float a=texture2D(atlas,uv).g; if(a<0.08) discard; gl_FragColor=vec4(vec3(0.3,1.0,0.5)*a*1.4,a); }' });
  const pts = new T.Points(geo, mat); pts.frustumCulled = false; pts.position.set(CX, 0, CZ); S.add(pts);
  // the screen fills from the bottom up too
  const ov = document.createElement('canvas'); ov.style.cssText = 'position:fixed;inset:0;width:100%;height:100%;pointer-events:none;z-index:9000;mix-blend-mode:screen;opacity:.85'; document.body.appendChild(ov); const q = ov.getContext('2d'); const fit = () => { ov.width = innerWidth; ov.height = innerHeight; }; fit(); const drops = []; const G = '01アイウエオカキク{}</>;=+$#';
  let t0 = app.t, phase = 0, eater = null, snout = new T.Vector3(); const fillT = 6.5, eatT = 2.8;
  const f = (dt, t) => { const k = t - t0;
    if (phase === 0) { const level = Math.min(1, k / fillT) * H; for (let i = 0; i < N; i++) { const sy = seed[i * 4 + 1]; const tgtY = sy <= level ? sy : -5; const ph = seed[i * 4 + 3]; pos[i * 3] = seed[i * 4] + Math.sin(t * 2 + ph) * 0.25; pos[i * 3 + 1] += ((tgtY + Math.sin(t * 3 + ph) * 0.18) - pos[i * 3 + 1]) * Math.min(1, dt * 5); pos[i * 3 + 2] = seed[i * 4 + 2] + Math.cos(t * 2.3 + ph) * 0.25; if (Math.random() < 0.02) gi[i] = Math.floor(Math.random() * 16); } geo.attributes.position.needsUpdate = true; geo.attributes.gi.needsUpdate = true; if (k > fillT) { phase = 1; t0 = t; eater = makeAnteater(); eater.position.set(-20, 0, 6); room.add(eater); app.toast('🐜🐽 …is that an ANTEATER?', 2600); } }
    else if (phase === 1) { const kk = Math.min(1, k / 1.6); eater.position.x = -20 + kk * 14; eater.userData.walk(t, 1); for (let i = 0; i < N; i++) { const ph = seed[i * 4 + 3]; pos[i * 3 + 1] += Math.sin(t * 3 + ph) * 0.01; } geo.attributes.position.needsUpdate = true; if (kk >= 1) { phase = 2; t0 = t; } }
    else if (phase === 2) { eater.userData.walk(t, 0); eater.userData.sniff(t); eater.userData.tip.getWorldPosition(snout); snout.x -= CX; snout.z -= CZ; const e = Math.min(1, k / eatT); for (let i = 0; i < N; i++) { const w = Math.min(1, Math.max(0, e * 1.6 - (seed[i * 4 + 1] / H) * 0.6)); const ease = w * w; pos[i * 3] += (snout.x - pos[i * 3]) * ease * Math.min(1, dt * 9); pos[i * 3 + 1] += (snout.y - pos[i * 3 + 1]) * ease * Math.min(1, dt * 9); pos[i * 3 + 2] += (snout.z - pos[i * 3 + 2]) * ease * Math.min(1, dt * 9); } geo.attributes.position.needsUpdate = true; mat.uniforms.sz.value = (MOB ? 46 : 60) * (1 - e * 0.7); if (e >= 1) { phase = 3; t0 = t; pts.visible = false; app.toast('🐽 *BURRRP.* Delicious code. All gone.', 3200); app.buzz && app.buzz(80); } }
    else if (phase === 3) { eater.userData.walk(t, 1); eater.rotation.y = Math.PI; eater.position.x -= dt * 7; if (k > 3) { room.remove(eater); S.remove(pts); geo.dispose(); mat.dispose(); ov.remove(); app.updaters = app.updaters.filter(z => z !== f); app.secret ? app.secret('pushed', 'You Pushed The Button', '<p>We said do not push it. You pushed it. An anteater had to come clean up. (Real anteaters eat up to 30,000 ants and termites a day, with a tongue about two feet long.)</p>') : null; done(); } }
    // overlay rain: rises from the bottom while filling, drains while the anteater eats
    q.clearRect(0, 0, ov.width, ov.height); const fs = 18, cols = Math.ceil(ov.width / fs); const top = phase === 0 ? ov.height * (1 - Math.min(1, k / fillT)) : phase === 1 ? 0 : phase === 2 ? ov.height * Math.min(1, k / eatT) : ov.height; if (top < ov.height) { q.font = `bold ${fs}px "Courier New", monospace`; for (let c = 0; c < cols; c += (MOB ? 2 : 1)) { for (let r = Math.floor(top / fs); r < ov.height / fs; r += 2) { if (((c * 7 + r * 13 + Math.floor(t * 8)) % 9) > 2) continue; q.fillStyle = `rgba(80,255,140,${0.22 + ((c + r) % 5) * 0.08})`; q.fillText(G[(c * 3 + r + Math.floor(t * 6)) % G.length], c * fs, r * fs); } } } };
  app.onUpdate(f); addEventListener('resize', fit, { once: true });
}
function makeAnteater() { const g = new T.Group(); const fur = M(0x6b5a4a, { roughness: 0.95 }), dark = M(0x2a2018, { roughness: 0.9 }), pale = M(0xd9cbb5, { roughness: 0.9 });
  const body = new T.Mesh(new T.SphereGeometry(1, 20, 14), fur); body.scale.set(1.6, 0.9, 0.75); body.position.y = 1.4; g.add(body); const stripe = new T.Mesh(new T.SphereGeometry(1, 16, 12, 0, Math.PI * 2, 0.9, 0.35), dark); stripe.scale.set(1.62, 0.92, 0.77); stripe.position.y = 1.4; stripe.rotation.z = -0.5; g.add(stripe); const band = new T.Mesh(new T.SphereGeometry(1, 16, 12, 0, Math.PI * 2, 1.25, 0.18), pale); band.scale.set(1.63, 0.93, 0.78); band.position.y = 1.4; band.rotation.z = -0.5; g.add(band);
  const head = new T.Group(); head.position.set(1.55, 1.55, 0); g.add(head); const hd = new T.Mesh(new T.SphereGeometry(0.42, 16, 12), fur); hd.scale.set(1.2, 0.85, 0.8); head.add(hd); const snout = new T.Mesh(new T.CylinderGeometry(0.06, 0.24, 1.7, 12), fur); snout.rotation.z = -Math.PI / 2 - 0.25; snout.position.set(1.15, -0.25, 0); head.add(snout); const tip = new T.Object3D(); tip.position.set(2.0, -0.48, 0); head.add(tip); const nose = new T.Mesh(new T.SphereGeometry(0.07, 8, 6), dark); nose.position.copy(tip.position); head.add(nose); for (const sz of [-1, 1]) { const e = new T.Mesh(new T.SphereGeometry(0.05, 8, 6), M(0x111111)); e.position.set(0.3, 0.12, sz * 0.24); head.add(e); const ear = new T.Mesh(new T.SphereGeometry(0.1, 8, 6), fur); ear.position.set(-0.2, 0.32, sz * 0.2); head.add(ear); }
  const tongue = new T.Mesh(new T.CylinderGeometry(0.02, 0.02, 0.8, 6), M(0xff6f91)); tongue.rotation.z = -Math.PI / 2; tongue.position.set(2.3, -0.55, 0); tongue.visible = false; head.add(tongue);
  const tail = new T.Group(); tail.position.set(-1.5, 1.6, 0); g.add(tail); for (let i = 0; i < 9; i++) { const s = new T.Mesh(new T.SphereGeometry(0.42 - i * 0.02, 10, 8), i % 2 ? fur : dark); s.scale.set(0.8, 1.3, 0.55); s.position.set(-i * 0.28, 0.25 + Math.sin(i * 0.5) * 0.3, 0); tail.add(s); }
  const legs = []; for (const [x, z] of [[0.9, 0.4], [0.9, -0.4], [-0.9, 0.4], [-0.9, -0.4]]) { const l = new T.Group(); l.position.set(x, 1.0, z); g.add(l); const m = new T.Mesh(new T.CylinderGeometry(0.16, 0.13, 1.0, 10), x > 0 ? pale : fur); m.position.y = -0.5; l.add(m); const paw = new T.Mesh(new T.SphereGeometry(0.17, 8, 6), dark); paw.position.y = -0.98; paw.scale.y = 0.5; l.add(paw); legs.push(l); }
  g.userData.tip = tip; g.userData.walk = (t, on) => { legs.forEach((l, i) => { l.rotation.z = on ? Math.sin(t * 9 + i * Math.PI * (i % 2 ? 1 : 0.5)) * 0.4 : 0; }); tail.rotation.y = Math.sin(t * 3) * 0.3; };
  g.userData.sniff = (t) => { head.rotation.z = -0.15 + Math.sin(t * 22) * 0.05; tongue.visible = Math.sin(t * 18) > 0; tongue.scale.y = 0.6 + Math.abs(Math.sin(t * 18)) * 0.8; };
  g.scale.setScalar(1.2); return g; }

/* Code Snake: a real retro game in a pop-up cabinet screen */
function snakeGame(app) { if (document.getElementById('wvm-snake')) return; const o = document.createElement('div'); o.id = 'wvm-snake'; o.style.cssText = 'position:fixed;inset:0;z-index:99990;background:rgba(2,6,23,.82);display:flex;align-items:center;justify-content:center;padding:12px;font-family:"Courier New",monospace'; o.innerHTML = '<div style="background:#120a24;border:6px solid #7c3aed;border-radius:18px;padding:14px;box-shadow:0 0 40px #7c3aed88;color:#3cff6e;text-align:center;max-width:96vw"><div style="display:flex;gap:10px;align-items:center;justify-content:space-between;margin-bottom:8px;font-weight:900"><span>CODE SNAKE</span><span id="sn-sc">SCORE 0</span><span id="sn-hi"></span><button id="sn-x" aria-label="Close" style="background:#fff;border:0;border-radius:8px;width:32px;height:32px;font-weight:900;cursor:pointer">✕</button></div><canvas id="sn-c" width="400" height="300" style="width:min(400px,86vw);height:auto;background:#031208;border-radius:8px;image-rendering:pixelated;touch-action:none"></canvas><div style="margin-top:8px;font-size:13px;color:#a7f3d0">Arrows / WASD, or swipe. Eat the pink bits. Don\'t bite yourself.</div></div>'; document.body.appendChild(o); app.paused = true;
  const c = o.querySelector('#sn-c'), q = c.getContext('2d'); const W = 20, H = 15; let sn = [[10, 7], [9, 7], [8, 7]], d = [1, 0], nd = [1, 0], food = [15, 7], score = 0, alive = true, acc = 0, last = performance.now(), raf = 0; const hi = () => +localStorage.getItem('wvm_snake_hi') || 0; o.querySelector('#sn-hi').textContent = 'HI ' + hi();
  const place = () => { do { food = [Math.floor(Math.random() * W), Math.floor(Math.random() * H)]; } while (sn.some(s => s[0] === food[0] && s[1] === food[1])); };
  const key = (e) => { const m = { ArrowUp: [0, -1], w: [0, -1], ArrowDown: [0, 1], s: [0, 1], ArrowLeft: [-1, 0], a: [-1, 0], ArrowRight: [1, 0], d: [1, 0] }[e.key.length === 1 ? e.key.toLowerCase() : e.key]; if (e.key === 'Escape') close(); if (!m) return; e.preventDefault(); e.stopPropagation(); if (m[0] !== -d[0] || m[1] !== -d[1]) nd = m; if (!alive) restart(); }; addEventListener('keydown', key, true);
  let sx = 0, sy = 0; c.addEventListener('pointerdown', (e) => { sx = e.clientX; sy = e.clientY; if (!alive) restart(); }); c.addEventListener('pointerup', (e) => { const dx = e.clientX - sx, dy = e.clientY - sy; if (Math.abs(dx) + Math.abs(dy) < 20) return; const m = Math.abs(dx) > Math.abs(dy) ? [Math.sign(dx), 0] : [0, Math.sign(dy)]; if (m[0] !== -d[0] || m[1] !== -d[1]) nd = m; });
  const restart = () => { sn = [[10, 7], [9, 7], [8, 7]]; d = [1, 0]; nd = [1, 0]; score = 0; alive = true; place(); };
  const loop = (now) => { if (!o.isConnected) return; const dt = (now - last) / 1000; last = now; acc += dt; const step = Math.max(0.06, 0.13 - score * 0.003); if (alive && acc > step) { acc = 0; d = nd; const h = [sn[0][0] + d[0], sn[0][1] + d[1]]; if (h[0] < 0 || h[1] < 0 || h[0] >= W || h[1] >= H || sn.some(s => s[0] === h[0] && s[1] === h[1])) { alive = false; if (score > hi()) localStorage.setItem('wvm_snake_hi', score); o.querySelector('#sn-hi').textContent = 'HI ' + hi(); } else { sn.unshift(h); if (h[0] === food[0] && h[1] === food[1]) { score++; place(); } else sn.pop(); } o.querySelector('#sn-sc').textContent = 'SCORE ' + score; }
    q.fillStyle = '#031208'; q.fillRect(0, 0, 400, 300); q.fillStyle = '#ff4f79'; q.fillRect(food[0] * 20 + 3, food[1] * 20 + 3, 14, 14); sn.forEach(([x, y], i) => { q.fillStyle = i ? '#3cff6e' : '#d1fae5'; q.fillRect(x * 20 + 1, y * 20 + 1, 18, 18); }); if (!alive) { q.fillStyle = 'rgba(0,0,0,.6)'; q.fillRect(0, 110, 400, 80); q.fillStyle = '#fff'; q.font = 'bold 26px "Courier New"'; q.textAlign = 'center'; q.fillText('GAME OVER · ' + score, 200, 148); q.font = '16px "Courier New"'; q.fillText('tap or press a key to play again', 200, 174); q.textAlign = 'left'; } raf = requestAnimationFrame(loop); };
  const close = () => { cancelAnimationFrame(raf); removeEventListener('keydown', key, true); o.remove(); app.paused = false; }; o.querySelector('#sn-x').onclick = close; raf = requestAnimationFrame(loop); }
