/* Character Studio (v42): the character screen opens full screen with a big live 3D preview of you
   that spins (drag to turn it), and tighter, smaller option buttons so there is room for everything. */
export function initStudio(app, E) {
  const { THREE: T, buildCharacter, CHARACTERS, addExtras, applyBuild, animatePerson } = E; const el = document.getElementById('wvm-selfie'); if (!el || el.dataset.studio) return; el.dataset.studio = '1';
  const css = document.createElement('style'); css.textContent = `#wvm-selfie.on{z-index:99990!important;padding:0!important;align-items:stretch!important;justify-content:stretch!important}#wvm-selfie.on .wvm-card{max-width:none!important;width:100vw!important;height:100dvh!important;max-height:none!important;border-radius:0!important;margin:0!important;padding:16px 18px 18px calc(min(42vw,560px) + 22px)!important;box-sizing:border-box;overflow:auto}#wvm-studio{position:fixed;left:0;top:0;bottom:0;width:min(42vw,560px);z-index:2;background:radial-gradient(circle at 50% 40%,#1e3a8a,#0b1230 70%);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;color:#fff;font-family:Poppins,Arial}#wvm-studio canvas{width:100%;height:78%;touch-action:none;cursor:grab}#wvm-studio .hint{font:700 12px Poppins,Arial;opacity:.8}#wvm-studio .nm{font:900 18px Poppins,Arial}#wvm-selfie .wvm-chars{grid-template-columns:repeat(auto-fill,minmax(84px,1fr))!important;gap:6px!important}#wvm-selfie .wvm-char{padding:6px 4px!important}#wvm-selfie .wvm-char .ic{font-size:24px!important}#wvm-selfie .wvm-char b{font-size:11.5px!important}#wvm-selfie .wvm-char small{font-size:9.5px!important}#wvm-selfie .wvm-looks button,#wvm-selfie .wvm-tabs button{padding:6px 10px!important;font-size:12px!important}
@media (max-width:820px){#wvm-selfie.on .wvm-card{padding:calc(36dvh + 10px) 12px 14px!important}#wvm-studio{right:0;width:auto;bottom:auto;height:36dvh}#wvm-studio canvas{height:82%}}`; document.head.appendChild(css);
  const box = document.createElement('div'); box.id = 'wvm-studio'; box.innerHTML = '<div class="nm" id="st-nm">You</div><canvas id="st-c" aria-label="Live preview of your character"></canvas><div class="hint">Live preview · drag to spin</div>'; el.appendChild(box);
  const cv = box.querySelector('#st-c'); let r = null, sc, cam, cur = null, yaw = 0, drag = null, raf = 0, rev = 0;
  const init = () => { if (r) return; r = new T.WebGLRenderer({ canvas: cv, antialias: true, alpha: true }); r.setPixelRatio(Math.min(2, devicePixelRatio)); r.outputColorSpace = T.SRGBColorSpace; sc = new T.Scene(); cam = new T.PerspectiveCamera(30, 1, 0.1, 50); sc.add(new T.HemisphereLight(0xffffff, 0x6677aa, 1.7)); const dl = new T.DirectionalLight(0xffffff, 1.6); dl.position.set(2, 4, 5); sc.add(dl); const fl = new T.Mesh(new T.CircleGeometry(1.4, 48), new T.MeshBasicMaterial({ color: 0x38f0ff, transparent: true, opacity: 0.18 })); fl.rotation.x = -Math.PI / 2; sc.add(fl); };
  const size = () => { if (!r) return; const w = cv.clientWidth || 300, h = cv.clientHeight || 400; r.setSize(w, h, false); cam.aspect = w / h; cam.updateProjectionMatrix(); };
  const rebuild = () => { if (!r) return; const my = ++rev; let av = {}; try { av = JSON.parse(localStorage.getItem('wvm_avatar') || '{}') || {}; } catch (e) { } const ch = CHARACTERS.find(c => c.id === (av.character || 'hero')) || CHARACTERS[0]; box.querySelector('#st-nm').textContent = (ch.icon || '') + ' ' + ch.name; let face = null; try { const f = localStorage.getItem('wvm_face'); if (f && ch.face) { face = new T.TextureLoader().load(f); face.colorSpace = T.SRGBColorSpace; } } catch (e) { }
    buildCharacter(ch, av, face).then(g => { if (my !== rev) return; try { addExtras(g, av); applyBuild(g, av.build); } catch (e) { } if (cur) sc.remove(cur); cur = g; sc.add(g); const hy = (g.userData.headY || 2) * (g.scale.y || 1); cam.position.set(0, hy * 0.62, hy * 2.3); cam.lookAt(0, hy * 0.5, 0); }).catch(() => { }); };
  const loop = (now) => { if (!el.classList.contains('on')) { raf = 0; return; } if (!drag) yaw += 0.006; if (cur) { cur.rotation.y = yaw; try { animatePerson(cur, now / 1000, 0); } catch (e) { } } r.render(sc, cam); raf = requestAnimationFrame(loop); };
  cv.onpointerdown = (e) => { cv.setPointerCapture(e.pointerId); drag = { x: e.clientX, y: yaw }; }; cv.onpointermove = (e) => { if (drag) yaw = drag.y + (e.clientX - drag.x) * 0.01; }; cv.onpointerup = () => drag = null;
  let deb = 0; const soon = () => { clearTimeout(deb); deb = setTimeout(rebuild, 250); };
  new MutationObserver(() => { if (el.classList.contains('on')) { init(); size(); rebuild(); if (!raf) raf = requestAnimationFrame(loop); } }).observe(el, { attributes: true, attributeFilter: ['class'] });
  el.addEventListener('click', soon); addEventListener('aou-avatar', soon); addEventListener('resize', size);
}
