/* 🏮 Sky Lantern Festival + 🌠 meteor showers (shared by both worlds). Write a wish, release a glowing lantern;
   everyone's recent wishes float overhead as lanterns, pulled from the FLAT 'wishes' group. */
import { THREE, makeSprite, isMobile } from './wvm-engine.js?v=51';
const T = THREE; const MOB = isMobile();
const glowTex = (() => { let t = null; return () => { if (t) return t; const c = document.createElement('canvas'); c.width = c.height = 128; const g = c.getContext('2d'); const gr = g.createRadialGradient(64, 64, 0, 64, 64, 64); gr.addColorStop(0, 'rgba(255,230,160,1)'); gr.addColorStop(0.4, 'rgba(255,180,80,.5)'); gr.addColorStop(1, 'rgba(255,150,50,0)'); g.fillStyle = gr; g.fillRect(0, 0, 128, 128); t = new T.CanvasTexture(c); return t; }; })();
export function initSky(app, { x, z, sb, me, toast, popup, celebrate, groundY }) {
  const S = app.scene; const gy = groundY || app.opts.groundY; const y0 = gy(x, z); const lanterns = []; const paper = new T.MeshStandardMaterial({ color: 0xffb060, emissive: 0xff9a2f, emissiveIntensity: 1.2, roughness: 0.9, transparent: true, opacity: 0.92, side: T.DoubleSide });
  const mkLantern = (px, py, pz, wish) => { const g = new T.Group(); const body = new T.Mesh(new T.CylinderGeometry(0.35, 0.3, 0.8, 8, 1, true), paper); body.position.y = 0.4; g.add(body); const top = new T.Mesh(new T.CylinderGeometry(0.35, 0.35, 0.05, 8), new T.MeshStandardMaterial({ color: 0x8a5a2b })); top.position.y = 0.8; g.add(top); const gl = new T.Sprite(new T.SpriteMaterial({ map: glowTex(), transparent: true, opacity: 0.8, depthWrite: false, blending: T.AdditiveBlending })); gl.scale.setScalar(2.6); gl.position.y = 0.4; g.add(gl); if (wish) { const tag = makeSprite('🏮 ' + wish.slice(0, 60), { scale: 2.8, accent: '#ffd23f' }); tag.position.y = 1.4; g.add(tag); } g.position.set(px, py, pz); S.add(g); lanterns.push({ g, t: 0, vx: (Math.random() - 0.5) * 0.4, vz: (Math.random() - 0.5) * 0.4, ph: Math.random() * 6 }); return g; };
  // the station
  const st = new T.Group(); st.position.set(x, y0, z); S.add(st); const base = new T.Mesh(new T.CylinderGeometry(1.4, 1.6, 0.4, 16), new T.MeshStandardMaterial({ color: 0x3a2410 })); base.position.y = 0.2; st.add(base); for (let i = 0; i < 5; i++) mkLantern(x + Math.cos(i * 1.26) * 1, y0 + 0.5, z + Math.sin(i * 1.26) * 1).userData.pinned = true; lanterns.forEach(l => l.pinned = true);
  const sign = makeSprite('🏮 SKY LANTERN FESTIVAL · write a wish, let it go', { scale: 4, accent: '#ffd23f' }); sign.position.set(0, 3.4, 0); st.add(sign); app.addObstacle && app.addObstacle(x, z, 1.8);
  const release = () => { popup('🏮 Write a wish', '<p>It floats up with everyone else\'s. Keep it kind.</p><input id="wish-t" maxlength="80" placeholder="I wish…" style="width:100%;box-sizing:border-box;border:1px solid #cbd5e1;border-radius:10px;padding:10px;font:700 15px Poppins,Arial"><p class="muted">Signed in? It also posts to the Sky Lantern Wishes feed so people can cheer you on.</p>', [{ label: '🏮 Let it go', fn: async () => { const w = (document.getElementById('wish-t') || {}).value || ''; const txt = w.trim(); const P = app.player.position; const l = mkLantern(P.x + 1, P.y + 0.6, P.z + 1, txt || null); l.userData.live = true; celebrate && celebrate('🏮'); toast(txt ? '🏮 Up it goes. ' + txt : '🏮 Up it goes.', 3500); const who = typeof me === 'function' ? me() : me; if (txt && sb && who) { try { await sb.from('feed_posts').insert({ user_id: who.id, kind: 'wish', text: txt, group_slug: 'wishes', public: true }); } catch (e) { } } } }]); };
  app.addInteractable && app.addInteractable(x, z + 2.2, 3, '🏮 Release a sky lantern', release); app.addHotspot && app.addHotspot(st, { fn: release });
  // everyone's recent wishes already in the sky
  if (sb) sb.from('feed_posts').select('text,created_at').eq('group_slug', 'wishes').eq('public', true).order('created_at', { ascending: false }).limit(MOB ? 8 : 18).then(({ data }) => { (data || []).forEach((w, i) => { const l = mkLantern(x + Math.cos(i * 1.7) * (12 + i * 2), y0 + 18 + i * 3, z + Math.sin(i * 1.7) * (12 + i * 2), w.text); l.userData.float = true; }); }).catch(() => { });
  // meteors
  const MN = 7; const mpos = new Float32Array(MN * 6); const mg = new T.BufferGeometry(); mg.setAttribute('position', new T.BufferAttribute(mpos, 3)); const meteors = new T.LineSegments(mg, new T.LineBasicMaterial({ color: 0xffffff, transparent: true, opacity: 0, blending: T.AdditiveBlending })); meteors.frustumCulled = false; S.add(meteors); let shower = 0, next = 40 + Math.random() * 60; const ms = [];
  app.onUpdate((dt, t) => { for (const l of lanterns) { if (l.pinned) { l.g.position.y = y0 + 0.5 + Math.sin(t * 2 + l.ph) * 0.05; continue; } if (l.g.userData.live) { l.t += dt; l.g.position.y += dt * (l.t < 3 ? 1.6 : 0.9); l.g.position.x += l.vx * dt; l.g.position.z += l.vz * dt; l.g.rotation.y += dt * 0.3; if (l.t > 60) { S.remove(l.g); l.dead = true; } } else if (l.g.userData.float) { l.g.position.y += Math.sin(t * 0.5 + l.ph) * dt * 0.3; l.g.position.x += l.vx * dt * 0.3; l.g.position.z += l.vz * dt * 0.3; } }
    for (let i = lanterns.length - 1; i >= 0; i--) if (lanterns[i].dead) lanterns.splice(i, 1);
    next -= dt; if (next <= 0 && shower <= 0) { shower = 9; next = 90 + Math.random() * 90; ms.length = 0; const P = app.player.position; for (let i = 0; i < MN; i++) ms.push({ x: P.x - 120 + Math.random() * 240, y: 120 + Math.random() * 60, z: P.z - 160 + Math.random() * 60, vx: 70 + Math.random() * 40, vy: -34 - Math.random() * 20, vz: 10, d: Math.random() * 6 }); toast('🌠 Meteor shower! Make a wish.', 3200); }
    if (shower > 0) { shower -= dt; let k = 0; for (const m of ms) { m.d -= dt; if (m.d > 0) { for (let q = 0; q < 6; q++) mpos[k * 6 + q] = 0; k++; continue; } m.x += m.vx * dt; m.y += m.vy * dt; m.z += m.vz * dt; mpos[k * 6] = m.x; mpos[k * 6 + 1] = m.y; mpos[k * 6 + 2] = m.z; mpos[k * 6 + 3] = m.x - m.vx * 0.12; mpos[k * 6 + 4] = m.y - m.vy * 0.12; mpos[k * 6 + 5] = m.z - m.vz * 0.12; k++; } mg.attributes.position.needsUpdate = true; meteors.material.opacity = Math.min(1, shower / 2); } else meteors.material.opacity = 0; });
  app.addPlace && app.addPlace({ id: 'lanterns', name: '🏮 Sky Lantern Festival · release a wish', icon: '🏮', x: x, z: z + 4, cat: 'Fun', top: true, keys: 'lantern festival wish sky meteor shower night', say: 'Write a wish and let it go. Watch the sky for meteors.' });
}
